In [1]:
import numpy as np
import pandas as pd
import re

In [2]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [3]:
df = pd.read_csv("../data/flats - flats.csv")

In [4]:
df.shape

(3028, 20)

- We have 3028 rows and 19 columns

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3028 entries, 0 to 3027
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    3028 non-null   object
 1   link             3028 non-null   object
 2   society          3027 non-null   object
 3   price            3008 non-null   object
 4   area             3015 non-null   object
 5   areaWithType     3009 non-null   object
 6   bedRoom          3009 non-null   object
 7   bathroom         3009 non-null   object
 8   balcony          3009 non-null   object
 9   additionalRoom   1695 non-null   object
 10  address          3003 non-null   object
 11  floorNum         3007 non-null   object
 12  facing           2128 non-null   object
 13  agePossession    3008 non-null   object
 14  nearbyLocations  2914 non-null   object
 15  description      3009 non-null   object
 16  furnishDetails   2204 non-null   object
 17  features         2595 non-null   object
 18  rating           2677 non-null   object
 19  property_id      3009 non-null   object
dtypes: object(20)
memory usage: 473.3+ KB

- Each columns are in string formate. 
- Some of the column have missing value(Aka Null values)

In [6]:
# Checking for duplicate values.
df.duplicated().sum()

0

- No duplicate values are present in our dataset.

In [7]:
# Checking for nulls values 
df.isnull().sum()

property_name         0
link                  0
society               1
price                20
area                 13
areaWithType         19
bedRoom              19
bathroom             19
balcony              19
additionalRoom     1333
address              25
floorNum             21
facing              900
agePossession        20
nearbyLocations     114
description          19
furnishDetails      824
features            433
rating              351
property_id          19
dtype: int64

- There are a lot of null values are present in our dataset.

In [8]:
df.head()

,property_name,link,society,price,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
0,2 BHK Flat in Krishna Colony,https://www.99acres.com/2-bhk-bedroom-apartmen...,maa bhagwati residency,45 Lac,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ...",C68850746
1,2 BHK Flat in Ashok Vihar,https://www.99acres.com/2-bhk-bedroom-apartmen...,Apna Enclave,50 Lac,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ...",H68850564
2,2 BHK Flat in Sohna,https://www.99acres.com/2-bhk-bedroom-apartmen...,Tulsiani Easy in Homes,40 Lac,"₹ 6,722/sq.ft.",Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ...",J68850120
3,2 BHK Flat in Sector 61 Gurgaon,https://www.99acres.com/2-bhk-bedroom-apartmen...,Smart World Orchard,1.47 Crore,"₹ 12,250/sq.ft.",Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN,S68849476
4,2 BHK Flat in Sector 92 Gurgaon,https://www.99acres.com/2-bhk-bedroom-apartmen...,Parkwood Westend,70 Lac,"₹ 5,204/sq.ft.",Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ...",L47956793

- In future we are not going to downing anything from the link. For our problem Link column is useless. So we'll drop this column.

In [9]:
# Columns to drop -> property_name, link, property_id
df.drop(columns=['link','property_id'], inplace=True)

In [10]:
df.head()

,property_name,society,price,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,45 Lac,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,Apna Enclave,50 Lac,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,Tulsiani Easy in Homes,40 Lac,"₹ 6,722/sq.ft.",Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,Smart World Orchard,1.47 Crore,"₹ 12,250/sq.ft.",Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,Parkwood Westend,70 Lac,"₹ 5,204/sq.ft.",Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [11]:
# Rename area column 
df.rename(columns={'area':'price_per_sqft'},inplace=True)
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,45 Lac,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,Apna Enclave,50 Lac,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,Tulsiani Easy in Homes,40 Lac,"₹ 6,722/sq.ft.",Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,Smart World Orchard,1.47 Crore,"₹ 12,250/sq.ft.",Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,Parkwood Westend,70 Lac,"₹ 5,204/sq.ft.",Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [12]:
df['society'].value_counts()

society
SS The Leaf3.8 ★                                     73
Tulip Violet4.3 ★                                    40
Shapoorji Pallonji Joyville Gurugram4.0 ★            39
Signature Global Park4.0 ★                           36
Shree Vardhman Victoria3.8 ★                         35
Tulip Violet4.2 ★                                    33
Emaar MGF Emerald Floors Premier3.8 ★                32
Smart World Orchard                                  32
Smart World Gems                                     32
DLF The Ultima4.0 ★                                  31
Paras Dews                                           31
DLF Regal Gardens3.9 ★                               30
M3M Woodshire4.0 ★                                   29
Shree Vardhman Flora3.8 ★                            29
Signature Global Solera3.7 ★                         28
La Vida by Tata Housing                              28
Godrej Nature Plus                                   27
Emaar Gurgaon Greens4.1 ★                            25
BPTP Terra3.8 ★                                      25
DLF New Town Heights 13.9 ★                          24
Vatika Gurgaon 213.7 ★                               24
Experion The Heartsong3.9 ★                          24
Eldeco Accolade3.8 ★                                 24
Bestech Park View Residency3.9 ★                     23
Emaar Palm Gardens4.1 ★                              22
ATS Triumph3.9 ★                                     22
Tata Primanti4.1 ★                                   22
M3M Heights                                          22
ROF Ananda                                           21
Sare Crescent Parc3.5 ★                              21
Experion Windchants3.8 ★                             20
Godrej 1014.0 ★                                      20
Antriksh Heights3.7 ★                                19
Sare Homes                                           19
Supertech Araville                                   19
ATS Tourmaline3.9 ★                                  18
Indiabulls Centrum Park3.7 ★                         18
Sobha City                                           18
CHD Avenue 713.6 ★                                   18
Mapsko Mount Ville4.1 ★                              18
Ambience Creacions                                   18
M3M Golfestate4.4 ★                                  17
M3M Skywalk                                          17
Godrej Summit3.7 ★                                   17
Conscient Heritage Max4.3 ★                          17
GLS Arawali Homes3.8 ★                               17
Pareena Coban Residences                             17
Bestech Park View Grand Spa4.3 ★                     16
HCBS Sports Ville3.6 ★                               16
Umang Monsoon Breeze                                 16
M3M Merlin3.7 ★                                      16
Godrej Oasis3.9 ★                                    16
Corona Optus3.9 ★                                    15
Emaar MGF The Palm Drive4.1 ★                        15
Ansal Heights 86                                     15
MVN Athens3.7 ★                                      14
The Close North4.0 ★                                 14
Ireo Skyon4.0 ★                                      14
Ireo Victory Valley4.1 ★                             14
Indiabulls Enigma                                    14
Ramsons Kshitij3.7 ★                                 14
Orchid Petals4.1 ★                                   14
Vatika The Seven Lamps3.8 ★                          14
Umang Winter Hills3.9 ★                              14
DLF The Primus3.9 ★                                  14
Imperia The Esfera                                   14
Puri Emerald Bay3.7 ★                                13
Central Park Flower Valley                           13
Ireo The Corridors                                   13
Bestech Park View Ananda4.2 ★                        13
Godrej Aria3.8 ★                                     11
DLF The Skycourt4.2 ★                                11
M3M Soulitude                                        11
TARC Maceo3.8 ★                                      11
Adani M2K Oyster Grande3.9 ★                         11
Alpha Corp GurgaonOne 844.0 ★                        11
Raheja Vedaanta3.6 ★                                 11
Breez Global Hill View                               11
SBTL Caladium                                        11
Pyramid Urban Homes 2                                10
Emaar MGF Palm Hills4.0 ★                            10
Zara Aavaas                                          10
Breez Global Heights4.2 ★                            10
Ramprastha The Edge Towers3.5 ★                      10
Capital Residences 360                               10
Puri Diplomatic Greens4.0 ★                          10
Signature Global Synera3.4 ★                         10
ATS Kocoon                                           10
DLF New Town Heights 24.0 ★                          10
ILD Greens4.1 ★                                      10
Godrej Air                                           10
Pivotal Devaan                                       10
Pareena Mi Casa                                       9
AIPL The Peaceful Homes3.9 ★                          9
Vatika City4.1 ★                                      9
Microtek Greenburg3.8 ★                               9
Bestech Park View Sanskruti4.2 ★                      9
Parsvnath Green Ville3.9 ★                            9
M3M Skycity                                           8
ss                                                    8
AVL 36 Gurgaon3.7 ★                                   8
Assotech Blith                                        8
Birla Navya                                           8
GLS Avenue 51                                         8
M3M Capital                                           8
Vatika Lifestyle Homes3.8 ★                           8
Orris Aster Court Premier                             8
Tulip Ivory3.5 ★                                      8
Bestech Altura                                        8
Emaar Digihomes                                       8
The Lions CGHS                                        8
Signature Andour Heights3.8 ★                         7
AIPL Zen Residences                                   7
Signature Global Orchard Avenue3.6 ★                  7
Vipul Lavanya3.9 ★                                    7
Orris Carnation Residency3.7 ★                        7
Sare Green ParC Phase 3                               7
Ireo The Grand Arch4.0 ★                              7
Signature Global City                                 7
Sare Crescent Parc Royal Greens Phase 1               7
Ansal Housing Highland Park                           7
Emaar Imperial Gardens3.8 ★                           7
Trisara Our Homes 3                                   7
Mapsko Casa Bella3.8 ★                                7
Greenopolis                                           6
HSIIDC Sidco Aravali                                  6
Signature Global Park 4                               6
Suncity Vatsal Valley                                 6
Sidhartha NCR One Phase 14.2 ★                        6
Hero Homes                                            6
Pioneer Araya3.8 ★                                    6
Bestech Park View City4.1 ★                           6
Shapoorji Pallonji Joyville Gurugram                  6
Kiran Residency                                       6
Pyramid Urban                                         6
BPTP Astaire Gardens3.7 ★                             6
Supertech Hues                                        6
Signature Global City 63A                             6
DLF Regency Park 13.6 ★                               6
Signature The Roselia3.6 ★                            6
Mapsko Royale Ville3.7 ★                              6
Bestech Park View Spa Next4.0 ★                       6
Parsvnath Exotica3.7 ★                                6
Ashiana Mulberry                                      6
M3M Sierra 68                                         6
Signature Global Grand IVA3.9 ★                       5
Ireo Uptown4.1 ★                                      5
Krisumi Waterfall Residences                          5
Pareena Laxmi Apartments3.6 ★                         5
Conscient Elevate                                     5
Central Park Resorts4.4 ★                             5
Central Park Flower Valley Aqua Front Towers          5
Tulip Monsella                                        5
M3M The Marina4.0 ★                                   5
Satya The Hermitage3.5 ★                              5
Apna Enclave                                          5
Godrej Habitat                                        5
Vatika City Homes3.9 ★                                5
Signature Global the Millennia                        5
DLF Park Place4.1 ★                                   5
DLF Regency Park 24.0 ★                               5
Signature Global City 37D Ph 2                        5
Green Court3.7 ★                                      5
Essel Towers                                          5
Silverglades The Melia                                5
Vatika Sovereign Park                                 5
Signature Global City 92                              5
Pioneer Park3.8 ★                                     5
Adani Brahma Samsara Vilasa                           5
Signature Global City 81                              5
Emaar MGF Emerald Estate3.8 ★                         5
ATS Marigold                                          5
Ashiana Anmol3.5 ★                                    5
Krrish Provence Estate                                4
Orris Aster Court                                     4
Signature The Serenas                                 4
Emaar Palm Heights                                    4
Godrej Icon                                           4
Global Hill View                                      4
ILD Grand                                             4
Corona Gracieux                                       4
Unitech Vistas                                        4
DLF New Town Heights3.7 ★                             4
HSIIDC Sidco Shivalik Apartments3.8 ★                 4
Unitech Fresco3.8 ★                                   4
Sare Petioles                                         4
Tata Gurgaon Gateway3.8 ★                             4
Railway Officers RPF Society                          4
Lotus Homz4.0 ★                                       4
Godrej Frontier3.7 ★                                  4
Raheja Navodaya3.6 ★                                  4
DLF The Skycourt                                      4
SS The Coralwood3.4 ★                                 4
Ramprastha Primera                                    4
Ramprastha Skyz                                       4
Prime Habitat                                         4
Maxworth City Residences                              3
Sidhartha NCR One                                     3
Unitech The Residences3.7 ★                           3
Deepak Minda                                          3
Tulip Purple                                          3
Raheja Atharva3.6 ★                                   3
Vatika Independent Floors3.8 ★                        3
Raheja Sampada                                        3
Unitech Uniworld Gardens3.8 ★                         3
Chintels Paradiso3.9 ★                                3
Puri Diplomatic Greens3.9 ★                           3
DLF Royalton Tower                                    3
Sidhartha NCR Greens4.3 ★                             3
Siddhartha Apartment                                  3
The Roselia 2                                         3
Kendriya Vihar4.1 ★                                   3
Valley View Estate                                    3
Whiteland Blissville                                  3
Signature Global Solera 2                             3
Pivotal Riddhi Siddhi                                 3
Guru Gram Haryana CGHS4.1 ★                           3
Unitech Sunbreeze                                     3
DLF The Arbour                                        3
Sare Green Parc 2                                     3
DLF Express Greens3.9 ★                               3
Tulip Petals3.6 ★                                     3
Shri Ram Apartments                                   3
Vatika Xpressions                                     3
Apex Our Homes                                        3
Shree Arihant Apartment                               3
Dhoot Time Residency4.0 ★                             3
Mahindra Aura4.2 ★                                    3
Shri Banke Bihari Society3.8 ★                        3
Sare Green Parc                                       3
Adani Aangan Arcade                                   3
AFNHB Jalvayu Vihar3.7 ★                              3
Sunischit Apartments                                  3
ATS Kocoon4.2 ★                                       3
Raheja Revanta                                        3
Spaze Privy3.9 ★                                      3
Tulip Lemon3.9 ★                                      3
Conscient Habitat3.6 ★                                3
Satya Element One                                     3
Suncity Platinum Towers                               3
Spaze Privy AT43.9 ★                                  3
Bestech Park View City 23.9 ★                         3
Spaze Privvy The Address3.9 ★                         3
Piedmont Taksila heights3.6 ★                         3
Paras Quartier                                        3
DLF Belvedere Towers3.8 ★                             3
AIPL Club Residences                                  3
My Home                                               3
Tulip White3.5 ★                                      3
Essel Tower                                           3
DLF Carlton Estate4.0 ★                               3
Smriti Apartment                                      3
Brisk Lumbini Terrace Homes                           3
SS Almeria                                            3
Sukhshanti Apartment                                  3
Unitech Heritage City                                 3
Jammu and Kashmir Bank Employees CGHS3.7 ★            3
Ambience Lagoon3.9 ★                                  3
Krrish Florence Estate                                3
DLF The Grove                                         3
Sapphire Eighty Three                                 3
Pyramid Elite                                         3
ROF Aalayas3.8 ★                                      2
Park Royal Apartment                                  2
BPTP Mansions Park Prime                              2
BPTP Pedestal                                         2
Sahara Grace                                          2
M3M Sky Lofts                                         2
Godrej Nature Plus Serenity                           2
DLF The Icon3.7 ★                                     2
Tulip Leaf                                            2
Emaar MGF The Enclave                                 2
Housing Board Colony                                  2
Mapsko Paradise3.9 ★                                  2
Professors Enclave CGHS                               2
Vipul Belmonte3.9 ★                                   2
Sidhivinayak Apartments                               2
Ardee City3.8 ★                                       2
Suncity Avenue 76                                     2
MRG World Ultimus                                     2
Samaspurkunj                                          2
HCBS Sports Ville                                     2
Paras Irene3.7 ★                                      2
Adani Aangan Galleria                                 2
Suncity Avenue 1023.9 ★                               2
Suncity Heights3.7 ★                                  2
DLF The Belaire3.9 ★                                  2
Ansal API Esencia3.7 ★                                2
Suposhaa Smartworld Orchard                           2
Raheja Atlantis3.8 ★                                  2
Palam Vihar Society                                   2
Ramprastha The Atrium3.4 ★                            2
Uphar lakshya homes                                   2
Mittal Surya Vihar                                    2
AWHO Shanti Vihar4.0 ★                                2
Vatika INXT Floors                                    2
Today Callidora                                       2
Ashiana Anmol                                         2
BPTP Amstoria3.8 ★                                    2
ss residency                                          2
Raheja Vanya                                          2
Central Park 2 Bellevue                               2
Tulip Orange3.9 ★                                     2
Chanderlok Society                                    2
Tulsiani Easy in Homes                                2
Ansal Heights3.2 ★                                    2
Residency Grand                                       2
Ramprastha City                                       2
Tulip Violet                                          2
Emaar MGF Palm Studios                                2
Landmark The Residency                                2
Mahindra Luminare4.0 ★                                2
Apartment                                             2
Vipul World Floors                                    2
CGHS Airport Apartment                                2
Ansal API Celebrity Suites                            2
The Penthouses at the Hibiscus                        2
SS Hibiscus                                           2
Puri The Aravallis                                    2
Silverglades Hightown Residences                      2
BPTP Freedom Park Life4.0 ★                           2
Vatika Emilia Floors3.7 ★                             2
M3M Latitude                                          2
Milan CGHS 9                                          2
Pioneer Urban Presidia                                2
Dlf City                                              2
Shapoorji Pallonji Joyville                           2
Element One Service                                   2
Oriental Valley CHS                                   2
Elan The Presidential                                 2
Viridian The Plaza 106                                2
The Close South3.9 ★                                  2
Breeze Global Heights                                 2
lagoon apartment                                      2
Supertech Hill Town                                   2
Aqua Front Towers                                     2
Lavanya Apartments                                    2
Ganga Apartment                                       2
Bhagwati Sadan                                        2
Signature Global The Millennia 3                      2
Supertech Hilltown                                    2
M3M Urbana                                            2
NBCC Heights3.9 ★                                     2
om appartments                                        2
Ambience Caitriona                                    2
Unitech Uniworld Gardens 23.4 ★                       2
Godrej Aria , sector 79 , Gurgaon                     2
Surendra Avenue 69                                    2
Bestech Park View Sanskruti4.1 ★                      2
DLF The Crest3.6 ★                                    2
M3M Ikonic                                            2
Bestech Spa Signature                                 2
Maruti Vihar                                          2
Vasant Appartments                                    2
Orchid Island4.2 ★                                    2
Green Campus CHS                                      2
ShreeRam Apartment II                                 1

In [13]:
df['society'].value_counts().shape

(639,)

In [14]:
df['society'] = df['society'].apply(lambda name: re.sub(r'\d+(\.\d+)?\s?★', '', str(name)).strip()).str.lower()

In [15]:
df['society'].value_counts().shape

(605,)

In [16]:
df['society'].value_counts()

society
tulip violet                                     75
ss the leaf                                      74
shapoorji pallonji joyville gurugram             45
dlf new town heights                             38
signature global park                            36
shree vardhman victoria                          35
smart world gems                                 32
emaar mgf emerald floors premier                 32
smart world orchard                              32
paras dews                                       31
dlf the ultima                                   31
m3m woodshire                                    30
dlf regal gardens                                30
shree vardhman flora                             29
signature global solera                          28
la vida by tata housing                          28
godrej nature plus                               27
emaar gurgaon greens                             25
bptp terra                                       25
experion the heartsong                           24
vatika gurgaon                                   24
eldeco accolade                                  24
bestech park view residency                      23
m3m heights                                      22
tata primanti                                    22
ats triumph                                      22
emaar palm gardens                               22
sare crescent parc                               21
godrej                                           21
rof ananda                                       21
experion windchants                              20
antriksh heights                                 19
supertech araville                               19
sare homes                                       19
indiabulls centrum park                          18
ats tourmaline                                   18
m3m skywalk                                      18
m3m golfestate                                   18
mapsko mount ville                               18
chd avenue                                       18
ambience creacions                               18
sobha city                                       18
hcbs sports ville                                18
gls arawali homes                                17
conscient heritage max                           17
pareena coban residences                         17
godrej summit                                    17
m3m merlin                                       16
godrej oasis                                     16
umang monsoon breeze                             16
bestech park view grand spa                      16
dlf the skycourt                                 15
ansal heights 86                                 15
corona optus                                     15
ramsons kshitij                                  15
emaar mgf the palm drive                         15
indiabulls enigma                                14
bestech park view ananda                         14
the close north                                  14
ireo victory valley                              14
orchid petals                                    14
vatika the seven lamps                           14
umang winter hills                               14
dlf the primus                                   14
mvn athens                                       14
ireo skyon                                       14
imperia the esfera                               14
ats kocoon                                       13
ireo the corridors                               13
central park flower valley                       13
puri diplomatic greens                           13
puri emerald bay                                 13
godrej aria                                      11
tarc maceo                                       11
raheja vedaanta                                  11
breez global heights                             11
dlf regency park                                 11
m3m soulitude                                    11
sbtl caladium                                    11
ild greens                                       11
alpha corp gurgaonone                            11
bestech park view sanskruti                      11
adani m2k oyster grande                          11
breez global hill view                           11
pivotal devaan                                   10
godrej air                                       10
capital residences 360                           10
ramprastha the edge towers                       10
zara aavaas                                      10
emaar mgf palm hills                             10
signature global synera                          10
pyramid urban homes 2                            10
parsvnath green ville                             9
microtek greenburg                                9
vatika city                                       9
aipl the peaceful homes                           9
pareena mi casa                                   9
bestech park view city                            9
assotech blith                                    8
m3m capital                                       8
vatika lifestyle homes                            8
emaar digihomes                                   8
tulip ivory                                       8
ss                                                8
avl 36 gurgaon                                    8
gls avenue 51                                     8
the lions cghs                                    8
birla navya                                       8
orris aster court premier                         8
m3m skycity                                       8
bestech altura                                    8
sare crescent parc royal greens phase 1           7
vipul lavanya                                     7
signature global city                             7
orris carnation residency                         7
signature global orchard avenue                   7
aipl zen residences                               7
mapsko casa bella                                 7
sare green parc phase 3                           7
ansal housing highland park                       7
emaar imperial gardens                            7
ireo the grand arch                               7
ashiana anmol                                     7
sidhartha ncr one phase                           7
trisara our homes 3                               7
signature andour heights                          7
green court                                       6
hero homes                                        6
signature global park 4                           6
signature global city 63a                         6
hsiidc sidco aravali                              6
signature the roselia                             6
mapsko royale ville                               6
suncity vatsal valley                             6
bptp astaire gardens                              6
ashiana mulberry                                  6
kiran residency                                   6
supertech hues                                    6
bestech park view spa next                        6
greenopolis                                       6
parsvnath exotica                                 6
pyramid urban                                     6
m3m sierra 68                                     6
pioneer araya                                     6
vatika sovereign park                             5
signature global city 37d ph 2                    5
tulip monsella                                    5
m3m the marina                                    5
signature global city 81                          5
central park flower valley aqua front towers      5
essel towers                                      5
unitech uniworld gardens                          5
adani brahma samsara vilasa                       5
satya the hermitage                               5
central park resorts                              5
emaar mgf emerald estate                          5
pareena laxmi apartments                          5
signature global city 92                          5
signature global grand iva                        5
apna enclave                                      5
vatika city homes                                 5
unitech fresco                                    5
dlf park place                                    5
pioneer park                                      5
ireo uptown                                       5
silverglades the melia                            5
godrej habitat                                    5
krisumi waterfall residences                      5
conscient elevate                                 5
ats marigold                                      5
signature global the millennia                    5
krrish provence estate                            4
railway officers rpf society                      4
raheja navodaya                                   4
afnhb jalvayu vihar                               4
signature the serenas                             4
ramprastha skyz                                   4
dlf the arbour                                    4
corona gracieux                                   4
emaar palm heights                                4
orris aster court                                 4
lotus homz                                        4
godrej icon                                       4
sare petioles                                     4
essel tower                                       4
kendriya vihar                                    4
prime habitat                                     4
tata gurgaon gateway                              4
hsiidc sidco shivalik apartments                  4
godrej frontier                                   4
ramprastha primera                                4
global hill view                                  4
ss the coralwood                                  4
ild grand                                         4
unitech vistas                                    4
valley view estate                                3
vatika xpressions                                 3
adani aangan arcade                               3
shri ram apartments                               3
raheja atharva                                    3
satya element one                                 3
spaze privy                                       3
jammu and kashmir bank employees cghs             3
tulip white                                       3
bhagwati sadan                                    3
tulip lemon                                       3
dlf express greens                                3
sare green parc 2                                 3
sidhartha ncr one                                 3
unitech sunbreeze                                 3
sare green parc                                   3
conscient habitat                                 3
chintels paradiso                                 3
vatika independent floors                         3
sidhartha ncr greens                              3
dhoot time residency                              3
piedmont taksila heights                          3
whiteland blissville                              3
sunischit apartments                              3
maxworth city residences                          3
signature global solera 2                         3
tulip purple                                      3
deepak minda                                      3
krrish florence estate                            3
spaze privvy the address                          3
unitech the residences                            3
raheja revanta                                    3
ambience lagoon                                   3
dlf royalton tower                                3
ss residency                                      3
the roselia 2                                     3
dlf carlton estate                                3
dlf the grove                                     3
guru gram haryana cghs                            3
smriti apartment                                  3
tulip petals                                      3
apex our homes                                    3
dlf belvedere towers                              3
shri banke bihari society                         3
paras quartier                                    3
aipl club residences                              3
pivotal riddhi siddhi                             3
pyramid elite                                     3
brisk lumbini terrace homes                       3
sapphire eighty three                             3
my home                                           3
spaze privy at                                    3
ss almeria                                        3
suncity platinum towers                           3
mahindra aura                                     3
shree arihant apartment                           3
sukhshanti apartment                              3
unitech heritage city                             3
raheja sampada                                    3
siddhartha apartment                              3
mapsko paradise                                   2
bptp mansions park prime                          2
orchid island                                     2
aqua front towers                                 2
m3m sky lofts                                     2
ramprastha the atrium                             2
tulip orange                                      2
signature global the millennia 3                  2
residency grand                                   2
dlf the icon                                      2
professors enclave cghs                           2
surendra avenue 69                                2
chanderlok society                                2
emaar mgf palm studios                            2
godrej aria , sector 79 , gurgaon                 2
tulsiani easy in homes                            2
vipul belmonte                                    2
emaar mgf the enclave                             2
adani aangan galleria                             2
uphar lakshya homes                               2
bptp amstoria                                     2
suncity avenue                                    2
dlf the belaire                                   2
park royal apartment                              2
the penthouses at the hibiscus                    2
ss hibiscus                                       2
ganga apartment                                   2
sidhivinayak apartments                           2
viridian the plaza 106                            2
tulip leaf                                        2
vatika emilia floors                              2
samaspurkunj                                      2
oriental valley chs                               2
ardee city                                        2
supertech hilltown                                2
suposhaa smartworld orchard                       2
mittal surya vihar                                2
emaar mgf emerald floors                          2
paras irene                                       2
dlf the crest                                     2
vatika inxt floors                                2
m3m latitude                                      2
the close south                                   2
shyam apartment                                   2
shree shyam residency                             2
sahara grace                                      2
pioneer urban presidia                            2
apartment                                         2
elan the presidential                             2
ansal heights                                     2
raheja atlantis                                   2
bptp freedom park life                            2
vipul world floors                                2
lagoon apartment                                  2
milan cghs 9                                      2
element one service                               2
ramprastha city                                   2
breeze global heights                             2
shapoorji pallonji joyville                       2
housing board colony                              2
nbcc heights                                      2
mahindra luminare                                 2
suncity heights                                   2
dlf city                                          2
landmark the residency                            2
puri the aravallis                                2
vasant appartments                                2
maruti vihar                                      2
silverglades hightown residences                  2
m3m urbana                                        2
m3m ikonic                                        2
green campus chs                                  2
om appartments                                    2
ambience caitriona                                2
supertech hill town                               2
mrg world ultimus                                 2
raheja vanya                                      2
suncity avenue 76                                 2
bptp pedestal                                     2
ansal api esencia                                 2
bestech spa signature                             2
awho shanti vihar                                 2
central park 2 bellevue                           2
palam vihar society                               2
today callidora                                   2
godrej nature plus serenity                       2
rof aalayas                                       2
lavanya apartments                                2
cghs airport apartment                            2
ansal api celebrity suites                        2
espire south                                      1
dnha group housing society                        1
the castle society                                1
raheja the vedaanta floors                        1
bptp park generations                             1
whiteland the aspen                               1
malibu towers                                     1
surbhi apartment                                  1
emaar the palm drive                              1
bsf chs                                           1
new colony, gurgaon                               1
park view apartments                              1
antriksh green                                    1
supertech new soft launch                         1
cghs hewo apartments                              1
511 sarahah tower                                 1
ansal height 86                                   1
kibithu villas                                    1
ansal plaza                                       1
raheja vedas                                      1
kamal residence                                   1
belgravia resort residences                       1
tulip yellow                                      1
ashray apartment                                  1
g l s arawali homes                               1
krishna appartment                                1
adarsh nagar                                      1
ansal sushant residency                           1
divya apartments                                  1
shreeram apartment ii                             1
ild grand centra                                  1
vidya apartment                                   1
proxima tower                                     1
palam vihar extension west zone rwa               1
maruti kunj                                       1
city shri ram apartments 1                        1
nan                                               1
ansals highland park                              1
shree balaji appartment                           1

In [17]:
df['price'].value_counts()

price
1.25 Crore          79
1.1 Crore           61
1.4 Crore           60
1.5 Crore           59
1.2 Crore           59
90 Lac              58
1.3 Crore           57
95 Lac              53
2 Crore             51
1.75 Crore          47
1 Crore             46
1.6 Crore           43
1.35 Crore          41
1.55 Crore          40
1.9 Crore           40
75 Lac              38
1.65 Crore          38
1.8 Crore           37
1.7 Crore           37
80 Lac              36
2.2 Crore           34
50 Lac              33
1.15 Crore          33
1.45 Crore          31
85 Lac              31
1.05 Crore          30
2.5 Crore           29
60 Lac              29
40 Lac              29
2.1 Crore           26
45 Lac              26
65 Lac              25
35 Lac              23
1.85 Crore          23
2.35 Crore          23
3 Crore             22
70 Lac              21
2.25 Crore          20
55 Lac              20
3.5 Crore           19
2.4 Crore           18
2.3 Crore           18
30 Lac              17
2.65 Crore          16
1.38 Crore          15
2.6 Crore           15
3.4 Crore           14
2.15 Crore          14
2.45 Crore          14
1.32 Crore          13
82 Lac              13
78 Lac              13
38 Lac              13
3.25 Crore          13
2.7 Crore           13
92 Lac              13
42 Lac              12
5 Crore             12
1.95 Crore          12
1.42 Crore          12
2.8 Crore           12
32 Lac              11
Price on Request    11
88 Lac              11
1.08 Crore          11
25 Lac              11
26 Lac              10
1.78 Crore          10
87 Lac              10
1.12 Crore          10
28 Lac              10
1.28 Crore          10
2.55 Crore          10
2.05 Crore           9
36 Lac               9
2.85 Crore           9
3.45 Crore           9
1.72 Crore           9
99 Lac               9
22 Lac               9
4 Crore              9
1.68 Crore           9
27 Lac               8
1.54 Crore           8
3.2 Crore            8
98 Lac               8
1.76 Crore           8
6 Crore              8
86 Lac               8
56 Lac               8
6.5 Crore            8
48 Lac               8
4.25 Crore           8
2.75 Crore           8
1.18 Crore           8
20 Lac               8
1.26 Crore           8
97 Lac               7
3.3 Crore            7
3.7 Crore            7
72 Lac               7
1.27 Crore           7
1.19 Crore           7
1.36 Crore           7
2.9 Crore            7
1.02 Crore           7
46 Lac               7
39 Lac               7
1.99 Crore           7
1.29 Crore           7
79 Lac               7
1.59 Crore           6
43 Lac               6
1.01 Crore           6
1.49 Crore           6
1.98 Crore           6
3.9 Crore            6
3.65 Crore           6
37 Lac               6
5.5 Crore            6
1.07 Crore           6
21 Lac               6
2.95 Crore           6
96 Lac               6
1.16 Crore           6
1.13 Crore           6
1.34 Crore           6
54 Lac               6
3.35 Crore           6
1.51 Crore           6
1.14 Crore           6
3.05 Crore           6
4.1 Crore            6
1.39 Crore           6
71.5 Lac             6
1.17 Crore           5
1.92 Crore           5
3.75 Crore           5
2.22 Crore           5
6.75 Crore           5
1.44 Crore           5
1.24 Crore           5
1.69 Crore           5
1.82 Crore           5
49 Lac               5
1.33 Crore           5
2.78 Crore           5
1.91 Crore           5
1.43 Crore           5
66 Lac               5
1.83 Crore           5
1.47 Crore           5
29 Lac               5
4.5 Crore            5
2.12 Crore           5
2.29 Crore           5
93 Lac               5
1.62 Crore           5
68 Lac               5
64 Lac               5
1.79 Crore           5
1.93 Crore           5
24 Lac               5
41.5 Lac             4
5.6 Crore            4
1.52 Crore           4
1.23 Crore           4
1.22 Crore           4
4.3 Crore            4
28.5 Lac             4
2.09 Crore           4
62 Lac               4
1.73 Crore           4
5.25 Crore           4
67 Lac               4
58 Lac               4
1.37 Crore           4
74 Lac               4
1.31 Crore           4
1.58 Crore           4
6.15 Crore           4
3.95 Crore           4
3.6 Crore            4
1.77 Crore           4
5.9 Crore            4
7 Crore              4
73 Lac               4
89 Lac               4
1.48 Crore           4
1.71 Crore           4
33 Lac               4
31 Lac               4
4.85 Crore           4
1.64 Crore           4
1.66 Crore           4
36.5 Lac             4
3.1 Crore            4
52 Lac               3
2.01 Crore           3
51 Lac               3
2.08 Crore           3
1.41 Crore           3
83 Lac               3
94 Lac               3
2.24 Crore           3
3.49 Crore           3
2.51 Crore           3
1.67 Crore           3
47 Lac               3
1.21 Crore           3
4.8 Crore            3
4.75 Crore           3
2.36 Crore           3
72.5 Lac             3
1.04 Crore           3
64.5 Lac             3
2.79 Crore           3
2.33 Crore           3
1.88 Crore           3
5.8 Crore            3
3.85 Crore           3
91 Lac               3
1.09 Crore           3
1.63 Crore           3
2.03 Crore           3
4.2 Crore            3
3.15 Crore           3
34 Lac               3
1.57 Crore           3
3.8 Crore            3
69 Lac               3
2.28 Crore           3
84 Lac               3
8 Crore              2
2.23 Crore           2
53 Lac               2
2.17 Crore           2
27.1 Lac             2
77.5 Lac             2
8.5 Crore            2
2.14 Crore           2
6.2 Crore            2
2.52 Crore           2
53.5 Lac             2
2.58 Crore           2
4.49 Crore           2
1.46 Crore           2
4.26 Crore           2
2.57 Crore           2
2.99 Crore           2
3.55 Crore           2
1.87 Crore           2
3.32 Crore           2
3.21 Crore           2
4.6 Crore            2
2.41 Crore           2
5.2 Crore            2
2.02 Crore           2
14 Crore             2
2.87 Crore           2
2.26 Crore           2
56.2 Lac             2
1.56 Crore           2
5.7 Crore            2
52.56 Lac            2
87.5 Lac             2
71 Lac               2
3.29 Crore           2
59 Lac               2
2.91 Crore           2
31.5 Lac             2
41 Lac               2
98.5 Lac             2
2.13 Crore           2
4.55 Crore           2
2.04 Crore           2
25.5 Lac             2
27.75 Lac            2
4.45 Crore           2
11 Crore             2
4.7 Crore            2
7.5 Crore            2
88.5 Lac             2
37.1 Lac             1
54.8 Lac             1
63.4 Lac             1
2.38 Crore           1
2.64 Crore           1
3.98 Crore           1
4.02 Crore           1
7.4 Crore            1
97.5 Lac             1
39.5 Lac             1
2.06 Crore           1
2.07 Crore           1
64.45 Lac            1
44 Lac               1
2.49 Crore           1
3.78 Crore           1
2.92 Crore           1
9 Crore              1
61 Lac               1
4.21 Crore           1
89.77 Lac            1
4.16 Crore           1
73.53 Lac            1
26.5 Lac             1
26.9 Lac             1
68.85 Lac            1
4.52 Crore           1
1.84 Crore           1
8.44 Crore           1
1.97 Crore           1
82.5 Lac             1
13.2 Crore           1
98.88 Lac            1
3.99 Crore           1
37.5 Lac             1
2.32 Crore           1
2.44 Crore           1
57 Lac               1
1.74 Crore           1
95.5 Lac             1
94.5 Lac             1
2.96 Crore           1
29.8 Lac             1
6.02 Crore           1
96.07 Lac            1
7.9 Crore            1
32.5 Lac             1
3.23 Crore           1
19 Lac               1
70.85 Lac            1
97.04 Lac            1
40.3 Lac             1
3.72 Crore           1
88.4 Lac             1
94.99 Lac            1
1.53 Crore           1
7.52 Crore           1
1.86 Crore           1
85.75 Lac            1
87.99 Lac            1
2.69 Crore           1
86.99 Lac            1
9.95 Crore           1
86.92 Lac            1
9.2 Crore            1
49.5 Lac             1
2.54 Crore           1
16 Lac               1
7.8 Crore            1
2.86 Crore           1
15 Crore             1
4.4 Crore            1
9.3 Crore            1
5.3 Crore            1
4.95 Crore           1
5.31 Crore           1
3.19 Crore           1
4.63 Crore           1
2.98 Crore           1
66.99 Lac            1
4.78 Crore           1
6.16 Crore           1
2.72 Crore           1
98.1 Lac             1
2.21 Crore           1
89.5 Lac             1
2.48 Crore           1
99.5 Lac             1
3.83 Crore           1
95.75 Lac            1
3.46 Crore           1
5.4 Crore            1
54.99 Lac            1
2.82 Crore           1
7.15 Crore           1
11.25 Crore          1
6.25 Crore           1
29.99 Lac            1
23 Lac               1
31.75 Lac            1
3.87 Crore           1
29.5 Lac             1
3.67 Crore           1
8.25 Crore           1
price                1
2.37 Crore           1
4.67 Crore           1
3.39 Crore           1
3.63 Crore           1
2.34 Crore           1
3.79 Crore           1
5.49 Crore           1
6.3 Crore            1
55.6 Lac             1
2.63 Crore           1
5.15 Crore           1
47.5 Lac             1
1.06 Crore           1
2.11 Crore           1
6.1 Crore            1
5.75 Crore           1
10 Crore             1
24.5 Lac             1
17.5 Lac             1
20.5 Lac             1
2.77 Crore           1
55.5 Lac             1
42.5 Lac             1
2.61 Crore           1
65.5 Lac             1
53.2 Lac             1
90.5 Lac             1
52.5 Lac             1
2.62 Crore           1
4.86 Crore           1
26.1 Lac             1
81 Lac               1
8.35 Crore           1
9.14 Crore           1
1.11 Crore           1
6.44 Crore           1
7.56 Crore           1
4.79 Crore           1
2.97 Crore           1
94.25 Lac            1
80.5 Lac             1
93.75 Lac            1
85.5 Lac             1
68.5 Lac             1
79.9 Lac             1
71.2 Lac             1
27.5 Lac             1
23.5 Lac             1
35.5 Lac             1
4.94 Crore           1
10.75 Crore          1
62.5 Lac             1
Name: count, dtype: int64

In [18]:
df[df['price'] == 'Price on Request']

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
25,5 BHK Flat in Sector 1 Gurgaon,the new people apartments,Price on Request,NaN,Built Up area: 4500 (418.06 sq.m.),5 Bedrooms,1 Bathroom,No Balcony,NaN,"Sector 1, Sector 1 Gurgaon, Gurgaon, Haryana",Ground of 1 Floors,NaN,undefined,"['Pooja Clinic', 'Dr. Sahil Clinic', 'Prakash ...",Best in class property available at sector 1 l...,NaN,NaN,NaN
1645,4 BHK Flat in Sector 50 Gurgaon,ss hibiscus,Price on Request,NaN,Carpet area: 4800 (445.93 sq.m.),4 Bedrooms,4 Bathrooms,3 Balconies,Servant Room,"Sector 50 Gurgaon, Gurgaon, Haryana",7th of 18 Floors,East,5 to 10 Year Old,"['Baani Square', 'SS Plaza', 'Good Earth City ...",4bedroom 4800sq.Ft middle floor apartment avai...,"['4 Fan', '8 Light', 'No AC', 'No Bed', 'No Ch...","['Lift(s)', 'Water purifier', 'Swimming Pool',...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
1973,1 BHK Flat in Sector 31 Gurgaon,raheja atlantis,Price on Request,NaN,Carpet area: 650 (60.39 sq.m.),1 Bedroom,1 Bathroom,1 Balcony,"Pooja Room,Study Room,Servant Room","Yes, Sector 31 Gurgaon, Gurgaon, Haryana",3rd of 15 Floors,East,0 to 1 Year Old,"['Huda Metro Station', 'Reliance Fresh, Indira...",It is my property and good condition and good ...,NaN,"['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area4 out of 5', 'Construction4 out of..."
2055,2 BHK Flat in Sector 79 Gurgaon,supertech araville,Price on Request,NaN,Built Up area: 1295 (120.31 sq.m.),2 Bedrooms,2 Bathrooms,No Balcony,NaN,"Sector 79, Sector 79 Gurgaon, Gurgaon, Haryana",15th of 15 Floors,NaN,undefined,NaN,"2 bath, unfurnished, 15th floor (Of 18), super...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle3 out of 5..."
2358,2 BHK Flat in Sector 37D Gurgaon,the millennia 2,Price on Request,NaN,Carpet area: 552 (51.28 sq.m.),2 Bedrooms,1 Bathroom,1 Balcony,NaN,"Sector 37D Gurgaon, Gurgaon, Haryana",13rd of 13 Floors,NaN,undefined,"['Shri Balaji Hospital and Trauma Center', 'Sh...","1 bath, unfurnished, 13th floor (Of 13), at se...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
2523,2 BHK Flat in Sector 95A Gurgaon,the roselia 2,Price on Request,NaN,Carpet area: 593 (55.09 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,NaN,"Sector 95a, Pataudi Road, Sector 95A Gurgaon, ...",14th of 14 Floors,NaN,undefined,NaN,Best in class property available at sector 95a...,NaN,NaN,"['Environment5 out of 5', 'Lifestyle4.5 out of..."
2550,3 BHK Flat in Sector-2 Sohna,supertech hilltown,Price on Request,NaN,Built Up area: 1720 (159.79 sq.m.),3 Bedrooms,3 Bathrooms,3 Balconies,NaN,"Sohna Sector 2,gurgaon, Sector-2 Sohna, Gurgao...",4th of 4 Floors,North-East,undefined,NaN,"3 bath, unfurnished, 4th floor (Of 4), overloo...",NaN,NaN,NaN
2641,2 BHK Flat in Sector 95A Gurgaon,the roselia 2,Price on Request,NaN,Carpet area: 593 (55.09 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,NaN,"Sector 95a, Pataudi Road, Sector 95A Gurgaon, ...",14th of 14 Floors,NaN,undefined,NaN,Best in class property available at sector 95a...,NaN,NaN,"['Environment5 out of 5', 'Safety5 out of 5', ..."
2960,3 BHK Flat in Sector 104 Gurgaon,godrej summit,Price on Request,NaN,Super Built up area 1647(153.01 sq.m.)Carpet a...,3 Bedrooms,3 Bathrooms,3 Balconies,NaN,"1402, Sector 104 Gurgaon, Gurgaon, Haryana",14th of 17 Floors,NaN,1 to 5 Year Old,"['MG Road Metro Station', 'The Esplanade Mall'...",We are the proud owners of this 3 bhk apartmen...,[],"['Intercom Facility', 'Lift(s)', 'Maintenance ...","['Management3 out of 5', 'Green Area4.5 out of..."
2973,4 BHK Flat in Gwal Pahari,krrish provence estate,Price on Request,NaN,Built Up area: 5800 (538.84 sq.m.),4 Bedrooms,5 Bathrooms,1 Balcony,NaN,"Gwal Pahari, Gurgaon, Haryana",17th of 24 Floors,NaN,Under Construction,"['Tniy Toons School', 'Pathways School Gurgoan...",Residential apartment for sell.Located on 17th...,NaN,NaN,NaN
2974,4 BHK Flat in Sector 95 Gurgaon,sidhartha ncr one phase,Price on Request,NaN,Super Built up area 2354(218.69 sq.m.),4 Bedrooms,4 Bathrooms,3+ Balconies,NaN,"Sector 95 Gurgaon, Gurgaon, Haryana",Ground of 3 Floors,North,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...","North facing entry, Very good layout, Excellen...",[],"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Management4 out of 5', 'Green Area4 out of 5..."

In [19]:
df = df[df['price'] != 'Price on Request']

In [21]:
df[df["price"].isna()]

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
18,2 BHK Flat in Sector 93 Gurgaon,signature global orchard avenue 2,NaN,NaN,Carpet area: 577.11 (53.62 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"L-1104, Sector 93 Gurgaon, Gurgaon, Haryana",11st of 14 Floors,East,Under Construction,"['Huda Metro Station', 'V3S Sapphire Ninety', ...",Looking for a budget-Friendly 2 bhk flat in a ...,NaN,"['Security / Fire Alarm', 'Feng Shui / Vaastu ...",NaN
2850,2 BHK Flat in Sector 107 Gurgaon,signature global solera,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2851,4 BHK Flat in Sector 53 Gurgaon,tulip monsella,NaN,"₹ 33,198/sq.ft.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2852,2 BHK Flat in New Palam Vihar,my home,NaN,"₹ 4,400/sq.ft.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2853,2 BHK Flat in Sohna,breez global hill view,NaN,"₹ 5,470/sq.ft.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2923,3 BHK Flat in Sector 99A Gurgaon,pareena coban residences,NaN,"₹ 5,759/sq.ft.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2924,1 BHK Flat in Golf Course Ext Road,ikon tower baani city centre,NaN,"₹ 12,437/sq.ft.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2925,2 BHK Flat in Sector 89 Gurgaon,greenopolis,NaN,"₹ 4,820/sq.ft.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2927,4 BHK Flat in C Block Sushant Lok Phase 1,maple heights,NaN,"₹ 8,888/sq.ft.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2928,2 BHK Flat in Sector 99 Gurgaon,assotech blith,NaN,"₹ 6,593/sq.ft.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2994,4 BHK Flat in DLF Phase 4,chanderlok society,NaN,"₹ 7,234/sq.ft.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2995,3 BHK Flat in Sector 9A Gurgaon,jammu and kashmir bank employees cghs,NaN,"₹ 6,129/sq.ft.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2996,3 BHK Flat in Sector 37C Gurgaon,ild greens,NaN,"₹ 4,723/sq.ft.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2997,3 BHK Flat in Adarsh Nagar,ss residency,NaN,"₹ 4,818/sq.ft.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2998,3 BHK Flat in Rajendra Park,uphar lakshya homes,NaN,"₹ 4,200/sq.ft.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2999,2 BHK Flat in Sector 79 Gurgaon,supertech araville,NaN,"₹ 9,000/sq.ft.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3000,3 BHK Flat in Sector 37C Gurgaon,corona optus,NaN,"₹ 6,361/sq.ft.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3001,3 BHK Flat in Sector 78 Gurgaon,umang monsoon breeze,NaN,"₹ 6,493/sq.ft.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3002,3 BHK Flat in Sector 88A Gurgaon,godrej oasis,NaN,"₹ 8,108/sq.ft.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3003,"2 BHK Flat in Godrej Aria , sector 79 , Gurgaon","godrej aria , sector 79 , gurgaon",NaN,"₹ 11,111/sq.ft.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
df.dropna(subset=["price"], inplace=True)

In [43]:
df[df['price'] == "[price]"]

Empty DataFrame
Columns: [property_name, society, price, price_per_sqft, areaWithType, bedRoom, bathroom, balcony, additionalRoom, address, floorNum, facing, agePossession, nearbyLocations, description, furnishDetails, features, rating]
Index: []

In [27]:
y = df['price'].str.split(' ')

In [30]:
value = y[0]

In [42]:
df['price'].str.split(' ').value_counts()

price
[1.25, Crore]     79
[1.1, Crore]      61
[1.4, Crore]      60
[1.5, Crore]      59
[1.2, Crore]      59
[90, Lac]         58
[1.3, Crore]      57
[95, Lac]         53
[2, Crore]        51
[1.75, Crore]     47
[1, Crore]        46
[1.6, Crore]      43
[1.35, Crore]     41
[1.9, Crore]      40
[1.55, Crore]     40
[1.65, Crore]     38
[75, Lac]         38
[1.7, Crore]      37
[1.8, Crore]      37
[80, Lac]         36
[2.2, Crore]      34
[50, Lac]         33
[1.15, Crore]     33
[1.45, Crore]     31
[85, Lac]         31
[1.05, Crore]     30
[2.5, Crore]      29
[60, Lac]         29
[40, Lac]         29
[45, Lac]         26
[2.1, Crore]      26
[65, Lac]         25
[2.35, Crore]     23
[35, Lac]         23
[1.85, Crore]     23
[3, Crore]        22
[70, Lac]         21
[2.25, Crore]     20
[55, Lac]         20
[3.5, Crore]      19
[2.3, Crore]      18
[2.4, Crore]      18
[30, Lac]         17
[2.65, Crore]     16
[2.6, Crore]      15
[1.38, Crore]     15
[3.4, Crore]      14
[2.45, Crore]     14
[2.15, Crore]     14
[38, Lac]         13
[78, Lac]         13
[92, Lac]         13
[82, Lac]         13
[1.32, Crore]     13
[3.25, Crore]     13
[2.7, Crore]      13
[1.42, Crore]     12
[1.95, Crore]     12
[5, Crore]        12
[42, Lac]         12
[2.8, Crore]      12
[25, Lac]         11
[1.08, Crore]     11
[88, Lac]         11
[32, Lac]         11
[87, Lac]         10
[1.28, Crore]     10
[2.55, Crore]     10
[28, Lac]         10
[1.78, Crore]     10
[26, Lac]         10
[1.12, Crore]     10
[99, Lac]          9
[22, Lac]          9
[36, Lac]          9
[2.85, Crore]      9
[2.05, Crore]      9
[4, Crore]         9
[3.45, Crore]      9
[1.72, Crore]      9
[1.68, Crore]      9
[4.25, Crore]      8
[3.2, Crore]       8
[27, Lac]          8
[48, Lac]          8
[1.76, Crore]      8
[1.54, Crore]      8
[1.26, Crore]      8
[6, Crore]         8
[20, Lac]          8
[98, Lac]          8
[2.75, Crore]      8
[86, Lac]          8
[56, Lac]          8
[6.5, Crore]       8
[1.18, Crore]      8
[97, Lac]          7
[1.19, Crore]      7
[72, Lac]          7
[3.7, Crore]       7
[1.27, Crore]      7
[1.36, Crore]      7
[2.9, Crore]       7
[1.99, Crore]      7
[3.3, Crore]       7
[1.02, Crore]      7
[46, Lac]          7
[79, Lac]          7
[39, Lac]          7
[1.29, Crore]      7
[1.13, Crore]      6
[1.34, Crore]      6
[1.39, Crore]      6
[1.49, Crore]      6
[1.51, Crore]      6
[5.5, Crore]       6
[3.9, Crore]       6
[1.16, Crore]      6
[3.05, Crore]      6
[1.98, Crore]      6
[43, Lac]          6
[3.65, Crore]      6
[37, Lac]          6
[2.95, Crore]      6
[1.01, Crore]      6
[21, Lac]          6
[1.59, Crore]      6
[96, Lac]          6
[54, Lac]          6
[1.14, Crore]      6
[1.07, Crore]      6
[4.1, Crore]       6
[3.35, Crore]      6
[71.5, Lac]        6
[1.92, Crore]      5
[1.43, Crore]      5
[93, Lac]          5
[1.83, Crore]      5
[29, Lac]          5
[3.75, Crore]      5
[6.75, Crore]      5
[1.47, Crore]      5
[4.5, Crore]       5
[1.82, Crore]      5
[1.44, Crore]      5
[64, Lac]          5
[1.33, Crore]      5
[2.78, Crore]      5
[1.62, Crore]      5
[68, Lac]          5
[1.24, Crore]      5
[2.29, Crore]      5
[1.79, Crore]      5
[2.22, Crore]      5
[66, Lac]          5
[49, Lac]          5
[1.69, Crore]      5
[24, Lac]          5
[1.93, Crore]      5
[1.91, Crore]      5
[2.12, Crore]      5
[1.17, Crore]      5
[1.58, Crore]      4
[1.73, Crore]      4
[1.77, Crore]      4
[4.85, Crore]      4
[1.64, Crore]      4
[5.25, Crore]      4
[3.6, Crore]       4
[1.52, Crore]      4
[1.37, Crore]      4
[62, Lac]          4
[4.3, Crore]       4
[41.5, Lac]        4
[1.22, Crore]      4
[58, Lac]          4
[1.31, Crore]      4
[2.09, Crore]      4
[33, Lac]          4
[7, Crore]         4
[73, Lac]          4
[36.5, Lac]        4
[1.48, Crore]      4
[5.6, Crore]       4
[28.5, Lac]        4
[3.1, Crore]       4
[5.9, Crore]       4
[67, Lac]          4
[89, Lac]          4
[74, Lac]          4
[31, Lac]          4
[1.66, Crore]      4
[6.15, Crore]      4
[3.95, Crore]      4
[1.71, Crore]      4
[1.23, Crore]      4
[5.8, Crore]       3
[2.33, Crore]      3
[91, Lac]          3
[1.41, Crore]      3
[52, Lac]          3
[2.79, Crore]      3
[72.5, Lac]        3
[3.85, Crore]      3
[1.63, Crore]      3
[34, Lac]          3
[2.24, Crore]      3
[83, Lac]          3
[47, Lac]          3
[1.21, Crore]      3
[4.75, Crore]      3
[2.36, Crore]      3
[94, Lac]          3
[1.04, Crore]      3
[64.5, Lac]        3
[69, Lac]          3
[84, Lac]          3
[51, Lac]          3
[2.08, Crore]      3
[1.88, Crore]      3
[2.01, Crore]      3
[2.51, Crore]      3
[2.03, Crore]      3
[4.8, Crore]       3
[1.09, Crore]      3
[3.15, Crore]      3
[1.67, Crore]      3
[1.57, Crore]      3
[3.8, Crore]       3
[3.49, Crore]      3
[2.28, Crore]      3
[4.2, Crore]       3
[1.46, Crore]      2
[2.17, Crore]      2
[53, Lac]          2
[27.1, Lac]        2
[77.5, Lac]        2
[6.2, Crore]       2
[8, Crore]         2
[2.52, Crore]      2
[4.49, Crore]      2
[2.23, Crore]      2
[2.58, Crore]      2
[53.5, Lac]        2
[8.5, Crore]       2
[2.14, Crore]      2
[4.26, Crore]      2
[2.57, Crore]      2
[2.99, Crore]      2
[3.55, Crore]      2
[1.87, Crore]      2
[3.32, Crore]      2
[3.21, Crore]      2
[4.6, Crore]       2
[2.41, Crore]      2
[5.2, Crore]       2
[2.02, Crore]      2
[14, Crore]        2
[2.87, Crore]      2
[2.26, Crore]      2
[56.2, Lac]        2
[1.56, Crore]      2
[5.7, Crore]       2
[52.56, Lac]       2
[87.5, Lac]        2
[71, Lac]          2
[3.29, Crore]      2
[59, Lac]          2
[2.91, Crore]      2
[31.5, Lac]        2
[41, Lac]          2
[98.5, Lac]        2
[2.13, Crore]      2
[4.55, Crore]      2
[2.04, Crore]      2
[25.5, Lac]        2
[27.75, Lac]       2
[4.45, Crore]      2
[11, Crore]        2
[4.7, Crore]       2
[7.5, Crore]       2
[88.5, Lac]        2
[37.1, Lac]        1
[54.8, Lac]        1
[63.4, Lac]        1
[2.38, Crore]      1
[2.64, Crore]      1
[3.98, Crore]      1
[4.02, Crore]      1
[7.4, Crore]       1
[97.5, Lac]        1
[39.5, Lac]        1
[2.06, Crore]      1
[2.07, Crore]      1
[64.45, Lac]       1
[44, Lac]          1
[2.49, Crore]      1
[3.78, Crore]      1
[2.92, Crore]      1
[9, Crore]         1
[61, Lac]          1
[4.21, Crore]      1
[89.77, Lac]       1
[4.16, Crore]      1
[73.53, Lac]       1
[26.5, Lac]        1
[26.9, Lac]        1
[68.85, Lac]       1
[4.52, Crore]      1
[1.84, Crore]      1
[8.44, Crore]      1
[1.97, Crore]      1
[82.5, Lac]        1
[13.2, Crore]      1
[98.88, Lac]       1
[3.99, Crore]      1
[37.5, Lac]        1
[2.32, Crore]      1
[2.44, Crore]      1
[57, Lac]          1
[1.74, Crore]      1
[95.5, Lac]        1
[94.5, Lac]        1
[2.96, Crore]      1
[29.8, Lac]        1
[6.02, Crore]      1
[96.07, Lac]       1
[7.9, Crore]       1
[32.5, Lac]        1
[3.23, Crore]      1
[19, Lac]          1
[70.85, Lac]       1
[97.04, Lac]       1
[40.3, Lac]        1
[3.72, Crore]      1
[88.4, Lac]        1
[94.99, Lac]       1
[1.53, Crore]      1
[7.52, Crore]      1
[1.86, Crore]      1
[85.75, Lac]       1
[87.99, Lac]       1
[2.69, Crore]      1
[86.99, Lac]       1
[9.95, Crore]      1
[86.92, Lac]       1
[9.2, Crore]       1
[49.5, Lac]        1
[2.54, Crore]      1
[16, Lac]          1
[7.8, Crore]       1
[2.86, Crore]      1
[15, Crore]        1
[4.4, Crore]       1
[9.3, Crore]       1
[5.3, Crore]       1
[4.95, Crore]      1
[5.31, Crore]      1
[3.19, Crore]      1
[4.63, Crore]      1
[2.98, Crore]      1
[66.99, Lac]       1
[4.78, Crore]      1
[6.16, Crore]      1
[2.72, Crore]      1
[98.1, Lac]        1
[2.21, Crore]      1
[89.5, Lac]        1
[2.48, Crore]      1
[99.5, Lac]        1
[3.83, Crore]      1
[95.75, Lac]       1
[3.46, Crore]      1
[5.4, Crore]       1
[54.99, Lac]       1
[2.82, Crore]      1
[7.15, Crore]      1
[11.25, Crore]     1
[6.25, Crore]      1
[29.99, Lac]       1
[23, Lac]          1
[31.75, Lac]       1
[3.87, Crore]      1
[29.5, Lac]        1
[3.67, Crore]      1
[8.25, Crore]      1
[price]            1
[2.37, Crore]      1
[4.67, Crore]      1
[3.39, Crore]      1
[3.63, Crore]      1
[2.34, Crore]      1
[3.79, Crore]      1
[5.49, Crore]      1
[6.3, Crore]       1
[55.6, Lac]        1
[2.63, Crore]      1
[5.15, Crore]      1
[47.5, Lac]        1
[1.06, Crore]      1
[2.11, Crore]      1
[6.1, Crore]       1
[5.75, Crore]      1
[10, Crore]        1
[24.5, Lac]        1
[17.5, Lac]        1
[20.5, Lac]        1
[2.77, Crore]      1
[55.5, Lac]        1
[42.5, Lac]        1
[2.61, Crore]      1
[65.5, Lac]        1
[53.2, Lac]        1
[90.5, Lac]        1
[52.5, Lac]        1
[2.62, Crore]      1
[4.86, Crore]      1
[26.1, Lac]        1
[81, Lac]          1
[8.35, Crore]      1
[9.14, Crore]      1
[1.11, Crore]      1
[6.44, Crore]      1
[7.56, Crore]      1
[4.79, Crore]      1
[2.97, Crore]      1
[94.25, Lac]       1
[80.5, Lac]        1
[93.75, Lac]       1
[85.5, Lac]        1
[68.5, Lac]        1
[79.9, Lac]        1
[71.2, Lac]        1
[27.5, Lac]        1
[23.5, Lac]        1
[35.5, Lac]        1
[4.94, Crore]      1
[10.75, Crore]     1
[62.5, Lac]        1
Name: count, dtype: int64

In [46]:
df = df[~df.apply(lambda row: row.astype(str).str.lower().eq(df.columns.str.lower()).any(), axis=1)]

In [47]:
def treat_price(x):
    if type(x) == float:
        return x
    else:
        if x[1] == 'Lac':
            return round(float(x[0])/100,2)
        else:
            return round(float(x[0]),2)

In [48]:
df['price'] = df['price'].str.split(' ').apply(treat_price)

In [49]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,"₹ 6,722/sq.ft.",Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,"₹ 12,250/sq.ft.",Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,"₹ 5,204/sq.ft.",Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [58]:
df['price_per_sqft'] = df['price_per_sqft'].str.split('/').str.get(0).str.replace('₹', '').str.replace(',','').astype('float')

In [59]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692.0,Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,6722.0,Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,12250.0,Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,5204.0,Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [61]:
df['bedRoom'].value_counts()

bedRoom
3 Bedrooms    1437
2 Bedrooms     943
4 Bedrooms     478
1 Bedroom      104
5 Bedrooms      31
6 Bedrooms       3
Name: count, dtype: int64

In [65]:
df['bedRoom'].isnull().sum()

0

In [67]:
df['bedRoom'] = df['bedRoom'].str.split(' ').str.get(0).astype('int')

In [68]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692.0,Carpet area: 650 (60.39 sq.m.),2,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,6722.0,Carpet area: 595 (55.28 sq.m.),2,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,12250.0,Carpet area: 1200 (111.48 sq.m.),2,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,5204.0,Super Built up area 1345(124.95 sq.m.),2,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [69]:
df['bathroom'].value_counts()

bathroom
2 Bathrooms    1043
3 Bathrooms     989
4 Bathrooms     636
5 Bathrooms     169
1 Bathroom      112
6 Bathrooms      42
7 Bathrooms       5
Name: count, dtype: int64

In [72]:
df['bathroom'] = df['bathroom'].str.split(' ').str.get(0).astype('int')

In [75]:
df['balcony'].value_counts()

balcony
3 Balconies     973
3+ Balconies    862
2 Balconies     749
1 Balcony       315
No Balcony       97
Name: count, dtype: int64

In [76]:
df['balcony'].isnull().sum()

0

In [79]:
df['balcony'] = df['balcony'].str.split(' ').str.get(0).str.replace('No','0')

In [80]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2,2,1,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692.0,Carpet area: 650 (60.39 sq.m.),2,2,1,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,6722.0,Carpet area: 595 (55.28 sq.m.),2,2,3,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,12250.0,Carpet area: 1200 (111.48 sq.m.),2,2,2,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,5204.0,Super Built up area 1345(124.95 sq.m.),2,2,3,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [81]:
df['additionalRoom'].value_counts()

additionalRoom
Servant Room                                     629
Study Room                                       232
Others                                           179
Pooja Room                                       132
Study Room,Servant Room                           81
Store Room                                        76
Pooja Room,Servant Room                           60
Servant Room,Others                               52
Servant Room,Pooja Room                           30
Study Room,Others                                 27
Pooja Room,Study Room,Servant Room,Others         25
Pooja Room,Study Room,Servant Room                24
Servant Room,Store Room                           19
Pooja Room,Study Room                             13
Pooja Room,Study Room,Servant Room,Store Room     12
Study Room,Pooja Room                              8
Servant Room,Study Room                            8
Study Room,Servant Room,Store Room                 7
Pooja Room,Store Room                              6
Pooja Room,Others                                  6
Others,Servant Room                                6
Servant Room,Study Room,Pooja Room,Store Room      6
Pooja Room,Servant Room,Others                     6
Study Room,Servant Room,Others                     5
Pooja Room,Store Room,Study Room,Servant Room      4
Pooja Room,Study Room,Store Room                   4
Servant Room,Pooja Room,Study Room,Store Room      3
Study Room,Pooja Room,Store Room                   3
Store Room,Servant Room                            3
Servant Room,Study Room,Store Room                 2
Pooja Room,Study Room,Others                       2
Study Room,Pooja Room,Servant Room                 2
Servant Room,Others,Store Room,Pooja Room          2
Servant Room,Others,Pooja Room                     2
Study Room,Servant Room,Pooja Room,Store Room      2
Others,Study Room                                  1
Servant Room,Study Room,Others                     1
Servant Room,Pooja Room,Study Room                 1
Servant Room,Study Room,Pooja Room                 1
Store Room,Pooja Room,Servant Room                 1
Servant Room,Pooja Room,Store Room,Study Room      1
Study Room,Store Room                              1
Store Room,Study Room                              1
Servant Room,Pooja Room,Store Room                 1
Study Room,Servant Room,Store Room,Pooja Room      1
Study Room,Servant Room,Pooja Room                 1
Pooja Room,Servant Room,Study Room,Store Room      1
Pooja Room,Study Room,Store Room,Servant Room      1
Store Room,Pooja Room                              1
Name: count, dtype: int64

In [82]:
df['additionalRoom'].value_counts().shape

(49,)

In [83]:
df['additionalRoom'].isnull().sum()

1304

In [84]:
df['additionalRoom'].fillna('not available',inplace=True)

In [85]:
df['additionalRoom'] = df['additionalRoom'].str.lower()

In [86]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2,2,1,not available,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692.0,Carpet area: 650 (60.39 sq.m.),2,2,1,not available,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,6722.0,Carpet area: 595 (55.28 sq.m.),2,2,3,not available,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,12250.0,Carpet area: 1200 (111.48 sq.m.),2,2,2,study room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,5204.0,Super Built up area 1345(124.95 sq.m.),2,2,3,study room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [87]:
df['floorNum']

0              4th   of 4 Floors
1              1st   of 3 Floors
2            12nd   of 14 Floors
3              2nd   of 4 Floors
4              5th   of 8 Floors
5              3rd   of 3 Floors
6             5th   of 25 Floors
7            14th   of 27 Floors
8              2nd   of 3 Floors
9            31st   of 40 Floors
10             1st   of 4 Floors
11            4th   of 13 Floors
12            4th   of 15 Floors
13            3rd   of 20 Floors
14           13rd   of 13 Floors
15           25th   of 25 Floors
16            Ground of 1 Floors
17           Ground of 14 Floors
19           12nd   of 13 Floors
20             4th   of 4 Floors
21           11st   of 22 Floors
22             4th   of 4 Floors
23           Ground of 14 Floors
24           10th   of 25 Floors
26             3rd   of 3 Floors
27           20th   of 20 Floors
28            5th   of 17 Floors
29            4th   of 12 Floors
30             4th   of 4 Floors
31             1st   of 4 Floors
32           12nd   of 12 Floors
33            8th   of 12 Floors
34           20th   of 20 Floors
35             8th   of 8 Floors
36           21st   of 24 Floors
37           Ground of 11 Floors
38            6th   of 19 Floors
39            1st   of 19 Floors
40             1st   of 3 Floors
41           12nd   of 17 Floors
42            6th   of 24 Floors
43            1st   of 25 Floors
44             2nd   of 4 Floors
45             1st   of 4 Floors
46            9th   of 29 Floors
47             5th   of 8 Floors
48           18th   of 32 Floors
49           29th   of 31 Floors
50             3rd   of 5 Floors
51            3rd   of 26 Floors
52            5th   of 18 Floors
53             1st   of 4 Floors
54            9th   of 12 Floors
55            6th   of 10 Floors
56             2nd   of 4 Floors
57           14th   of 14 Floors
58            1st   of 11 Floors
59            8th   of 14 Floors
60             2nd   of 2 Floors
61           12nd   of 12 Floors
62            4th   of 14 Floors
63            1st   of 18 Floors
64            7th   of 19 Floors
65             3rd   of 4 Floors
66            5th   of 20 Floors
67            9th   of 15 Floors
68           14th   of 17 Floors
69           14th   of 14 Floors
70           15th   of 20 Floors
71            6th   of 14 Floors
72            6th   of 14 Floors
73            2nd   of 12 Floors
74            3rd   of 11 Floors
75             2nd   of 4 Floors
76            4th   of 13 Floors
77             3rd   of 4 Floors
78            6th   of 14 Floors
79            8th   of 13 Floors
80             2nd   of 4 Floors
81             4th   of 4 Floors
82           Ground of 14 Floors
83           11st   of 11 Floors
84             1st   of 3 Floors
85           11st   of 13 Floors
86           21st   of 41 Floors
87            4th   of 13 Floors
88             2nd   of 5 Floors
89             2nd   of 3 Floors
90             4th   of 4 Floors
91           32nd   of 32 Floors
92             2nd   of 4 Floors
93             2nd   of 2 Floors
94             2nd   of 2 Floors
95           11st   of 11 Floors
96           23rd   of 26 Floors
97            6th   of 12 Floors
98            9th   of 20 Floors
99             1st   of 4 Floors
100           5th   of 15 Floors
101            43   of 47 Floors
102            1st   of 1 Floors
103            1st   of 4 Floors
104           1st   of 13 Floors
105          11st   of 12 Floors
106          14th   of 24 Floors
107           9th   of 30 Floors
108           8th   of 14 Floors
109            9th   of 9 Floors
110           2nd   of 12 Floors
111           4th   of 14 Floors
112          32nd   of 55 Floors
113            43   of 47 Floors
114           2nd   of 19 Floors
115            3rd   of 4 Floors
116           8th   of 22 Floors
117            3rd   of 4 Floors
118          20th   of 32 Floors
119           2nd   of 17 Floors
120        Basement of 28 Floors
121           4th   of 10 Floors
122           Ground of 4 Floors
123            3rd   of 4 Floors
124            4th   of 8 Floors
125            3rd   of 4 Floors
126           6th   of 20 Floors
127          13rd   of 13 Floors
128          13rd   of 13 Floors
129          16th   of 16 Floors
130            3rd   of 4 Floors
131           Ground of 1 Floors
132          11st   of 14 Floors
133           2nd   of 14 Floors
134          12nd   of 12 Floors
135            2nd   of 4 Floors
136           1st   of 18 Floors
137           4th   of 12 Floors
138          11st   of 13 Floors
139           5th   of 17 Floors
140           1st   of 25 Floors
141          12nd   of 16 Floors
142          16th   of 18 Floors
143            6th   of 6 Floors
144            2nd   of 2 Floors
145            3rd   of 4 Floors
146          11st   of 25 Floors
147          10th   of 18 Floors
148           2nd   of 25 Floors
149            4th   of 4 Floors
150          19th   of 41 Floors
151            1st   of 3 Floors
152            8th   of 8 Floors
153          18th   of 19 Floors
154          10th   of 16 Floors
155           7th   of 20 Floors
156           2nd   of 14 Floors
157          10th   of 10 Floors
158           5th   of 12 Floors
159          10th   of 20 Floors
160          20th   of 34 Floors
161          20th   of 22 Floors
162            3rd   of 4 Floors
163          13rd   of 14 Floors
164           3rd   of 19 Floors
165           7th   of 18 Floors
166            4th   of 4 Floors
167           4th   of 14 Floors
168            2nd   of 4 Floors
169           2nd   of 25 Floors
170           4th   of 14 Floors
171           3rd   of 19 Floors
172            1st   of 1 Floors
173            2nd   of 4 Floors
174          11st   of 15 Floors
175          11st   of 21 Floors
176          16th   of 22 Floors
177           8th   of 10 Floors
178           1st   of 35 Floors
179          18th   of 25 Floors
180           8th   of 15 Floors
181                          NaN
182           2nd   of 16 Floors
183          17th   of 17 Floors
184          23rd   of 28 Floors
185          10th   of 18 Floors
186          30th   of 32 Floors
187            4th   of 4 Floors
188            2nd   of 3 Floors
189           Ground of 3 Floors
190          Ground of 14 Floors
191            1st   of 4 Floors
192            1st   of 1 Floors
193          11st   of 36 Floors
194          11st   of 13 Floors
195           Ground of 3 Floors
196          19th   of 19 Floors
197          28th   of 28 Floors
198            4th   of 4 Floors
199            9th   of 9 Floors
200            7th   of 7 Floors
201         Basement of 4 Floors
202          15th   of 15 Floors
203           2nd   of 34 Floors
204          Ground of 14 Floors
205           9th   of 10 Floors
206           1st   of 15 Floors
207            1st   of 1 Floors
208           4th   of 34 Floors
209           4th   of 18 Floors
210           3rd   of 15 Floors
211            1st   of 4 Floors
212           1st   of 19 Floors
213     Lower Ground of 4 Floors
214          13rd   of 13 Floors
215           4th   of 40 Floors
216           6th   of 18 Floors
217          20th   of 47 Floors
218          27th   of 48 Floors
219            6th   of 7 Floors
220          33rd   of 48 Floors
221          35th   of 35 Floors
222          26th   of 47 Floors
223           Ground of 1 Floors
224            2nd   of 4 Floors
225           4th   of 14 Floors
226          10th   of 17 Floors
227          11st   of 14 Floors
228          10th   of 22 Floors
229          Ground of 24 Floors
230           3rd   of 12 Floors
231           7th   of 25 Floors
232           8th   of 14 Floors
233            2nd   of 4 Floors
234           3rd   of 18 Floors
235            1st   of 4 Floors
236           9th   of 14 Floors
237          14th   of 15 Floors
238            4th   of 4 Floors
239           8th   of 25 Floors
240          10th   of 14 Floors
241           3rd   of 14 Floors
242            3rd   of 4 Floors
243            2nd   of 4 Floors
244           3rd   of 14 Floors
245            7th   of 7 Floors
246            2nd   of 4 Floors
247           3rd   of 15 Floors
248           8th   of 34 Floors
249          12nd   of 14 Floors
250           8th   of 42 Floors
251            1st   of 4 Floors
252           1st   of 22 Floors
253          26th   of 34 Floors
254          21st   of 29 Floors
255           8th   of 32 Floors
256           2nd   of 14 Floors
257           1st   of 12 Floors
258            2nd   of 4 Floors
259          39th   of 40 Floors
260           1st   of 14 Floors
261           8th   of 10 Floors
262            2nd   of 3 Floors
263            3rd   of 4 Floors
264            7th   of 9 Floors
265           4th   of 15 Floors
266          22nd   of 24 Floors
267          14th   of 20 Floors
268          11st   of 15 Floors
269          17th   of 17 Floors
270           3rd   of 12 Floors
271          12nd   of 13 Floors
272           8th   of 19 Floors
273           3rd   of 14 Floors
274          14th   of 14 Floors
275            7th   of 7 Floors
276           9th   of 15 Floors
277           2nd   of 17 Floors
278            3rd   of 3 Floors
279            6th   of 6 Floors
280          16th   of 16 Floors
281          12nd   of 12 Floors
282            1st   of 1 Floors
283            4th   of 4 Floors
284          17th   of 17 Floors
285           7th   of 26 Floors
287          11st   of 30 Floors
288            4th   of 8 Floors
289           1st   of 14 Floors
290           6th   of 14 Floors
291            1st   of 3 Floors
292          17th   of 17 Floors
293            1st   of 7 Floors
294          16th   of 18 Floors
295          19th   of 40 Floors
296          31st   of 32 Floors
297          14th   of 22 Floors
298           5th   of 19 Floors
299            2nd   of 4 Floors
300            1st   of 4 Floors
301           1st   of 10 Floors
302          15th   of 32 Floors
303            1st   of 7 Floors
304            1st   of 2 Floors
305            2nd   of 3 Floors
306          11st   of 14 Floors
307           9th   of 26 Floors
308          33rd   of 42 Floors
309          14th   of 18 Floors
310            4th   of 4 Floors
311           5th   of 14 Floors
312          18th   of 18 Floors
313           1st   of 14 Floors
314          20th   of 23 Floors
315           9th   of 14 Floors
316          18th   of 19 Floors
317           8th   of 32 Floors
318           4th   of 15 Floors
319           9th   of 17 Floors
320            4th   of 8 Floors
321           1st   of 14 Floors
322           6th   of 14 Floors
323            1st   of 3 Floors
324          19th   of 40 Floors
325          31st   of 32 Floors
326           5th   of 19 Floors
327            1st   of 4 Floors
328           1st   of 10 Floors
329          15th   of 32 Floors
330            1st   of 7 Floors
331            1st   of 2 Floors
332            2nd   of 3 Floors
333          11st   of 14 Floors
334           9th   of 26 Floors
335          14th   of 18 Floors
336           5th   of 14 Floors
337           1st   of 14 Floors
338           9th   of 14 Floors
339          18th   of 19 Floors
340           4th   of 15 Floors
341           1st   of 44 Floors
342          20th   of 20 Floors
343          24th   of 31 Floors
344           2nd   of 15 Floors
345            4th   of 4 Floors
346          14th   of 14 Floors
347           9th   of 16 Floors
348          14th   of 15 Floors
349           4th   of 14 Floors
350          26th   of 30 Floors
351           2nd   of 16 Floors
352          14th   of 24 Floors
353          17th   of 17 Floors
354           2nd   of 14 Floors
355          25th   of 25 Floors
356           9th   of 22 Floors
357            4th   of 4 Floors
358           6th   of 17 Floors
359           5th   of 14 Floors
360           4th   of 14 Floors
361          14th   of 21 Floors
362          15th   of 19 Floors
363           7th   of 14 Floors
364            2nd   of 4 Floors
365          16th   of 20 Floors
366          24th   of 51 Floors
367          10th   of 20 Floors
368            2nd   of 4 Floors
369           2nd   of 12 Floors
370           2nd   of 24 Floors
371           1st   of 19 Floors
372           8th   of 18 Floors
373          12nd   of 22 Floors
374          18th   of 19 Floors
375            1st   of 4 Floors
376           2nd   of 36 Floors
377            3rd   of 4 Floors
378          11st   of 11 Floors
379           7th   of 20 Floors
380           5th   of 18 Floors
381           6th   of 12 Floors
382          19th   of 31 Floors
383          25th   of 25 Floors
384          10th   of 10 Floors
385          10th   of 10 Floors
386            3rd   of 9 Floors
387           8th   of 14 Floors
388           5th   of 12 Floors
389           4th   of 22 Floors
390           1st   of 35 Floors
391          10th   of 14 Floors
392          16th   of 24 Floors
393          10th   of 14 Floors
394            3rd   of 8 Floors
395          17th   of 19 Floors
396           9th   of 14 Floors
397          11st   of 26 Floors
398          19th   of 20 Floors
399          Ground of 16 Floors
400          Ground of 23 Floors
401           8th   of 26 Floors
402           4th   of 11 Floors
403          30th   of 32 Floors
404          16th   of 51 Floors
405          18th   of 21 Floors
406           2nd   of 10 Floors
407           7th   of 10 Floors
408            2nd   of 4 Floors
409          10th   of 10 Floors
410           9th   of 12 Floors
411           6th   of 10 Floors
412          14th   of 29 Floors
413          25th   of 36 Floors
414           7th   of 23 Floors
415           4th   of 14 Floors
416            7th   of 9 Floors
417          18th   of 32 Floors
418          12nd   of 17 Floors
419            3rd   of 4 Floors
420          21st   of 28 Floors
421          14th   of 28 Floors
422           5th   of 25 Floors
423           3rd   of 19 Floors
424          19th   of 24 Floors
425          10th   of 14 Floors
426            5th   of 9 Floors
427          10th   of 30 Floors
428           7th   of 14 Floors
429          11st   of 20 Floors
430           2nd   of 17 Floors
431            2nd   of 4 Floors
432           7th   of 14 Floors
433           6th   of 14 Floors
434          11st   of 17 Floors
435           9th   of 14 Floors
436            4th   of 4 Floors
437          14th   of 20 Floors
438            5th   of 5 Floors
439            1st   of 4 Floors
440          16th   of 27 Floors
441           1st   of 10 Floors
442          18th   of 32 Floors
443           6th   of 16 Floors
444           8th   of 13 Floors
445            4th   of 4 Floors
446           7th   of 27 Floors
447            9th   of 9 Floors
448            3rd   of 4 Floors
449          11st   of 18 Floors
450          17th   of 25 Floors
451           7th   of 42 Floors
452           5th   of 30 Floors
453          16th   of 32 Floors
454           2nd   of 16 Floors
455           8th   of 29 Floors
456            2nd   of 8 Floors
457           3rd   of 32 Floors
458           6th   of 26 Floors
459          Ground of 14 Floors
460           2nd   of 12 Floors
461          15th   of 40 Floors
462          10th   of 25 Floors
463          11st   of 30 Floors
464          10th   of 15 Floors
465           4th   of 12 Floors
466           3rd   of 18 Floors
467           9th   of 19 Floors
468           8th   of 16 Floors
469           7th   of 12 Floors
470           5th   of 12 Floors
471           7th   of 14 Floors
472           7th   of 14 Floors
473           9th   of 14 Floors
474           2nd   of 20 Floors
475           5th   of 18 Floors
476          11st   of 20 Floors
477           8th   of 11 Floors
478           7th   of 17 Floors
479          20th   of 26 Floors
480          10th   of 12 Floors
481           7th   of 29 Floors
482          10th   of 51 Floors
483          16th   of 21 Floors
484           8th   of 21 Floors
485           1st   of 14 Floors
486          18th   of 30 Floors
487          15th   of 30 Floors
488          25th   of 30 Floors
489           5th   of 29 Floors
490           9th   of 26 Floors
491           5th   of 26 Floors
492           7th   of 26 Floors
493           7th   of 26 Floors
494           7th   of 26 Floors
495          12nd   of 30 Floors
496           5th   of 15 Floors
497           4th   of 10 Floors
498           6th   of 10 Floors
499            3rd   of 6 Floors
500          10th   of 18 Floors
501          15th   of 28 Floors
502          15th   of 28 Floors
503          10th   of 14 Floors
504           9th   of 28 Floors
505          10th   of 15 Floors
506          10th   of 21 Floors
507           9th   of 12 Floors
508           Ground of 4 Floors
509            1st   of 2 Floors
510          11st   of 12 Floors
511          17th   of 24 Floors
512           1st   of 26 Floors
513          Ground of 18 Floors
514           7th   of 14 Floors
515            5th   of 8 Floors
516          12nd   of 29 Floors
517          14th   of 29 Floors
518          14th   of 29 Floors
519           9th   of 21 Floors
520          19th   of 29 Floors
521           8th   of 14 Floors
522          14th   of 29 Floors
523           8th   of 14 Floors
524            2nd   of 5 Floors
525           9th   of 13 Floors
526           5th   of 14 Floors
527          Ground of 14 Floors
528            6th   of 8 Floors
529          10th   of 19 Floors
530           6th   of 10 Floors
531           8th   of 18 Floors
532           9th   of 24 Floors
533           9th   of 26 Floors
534          12nd   of 17 Floors
535          11st   of 16 Floors
536           6th   of 16 Floors
537          15th   of 39 Floors
538           7th   of 12 Floors
539           8th   of 19 Floors
540           8th   of 26 Floors
541           3rd   of 26 Floors
542          10th   of 26 Floors
543           1st   of 26 Floors
544           4th   of 26 Floors
545           5th   of 12 Floors
546           2nd   of 12 Floors
547          20th   of 40 Floors
548          13rd   of 40 Floors
549           8th   of 40 Floors
550           8th   of 19 Floors
551          16th   of 19 Floors
552          12nd   of 18 Floors
553          10th   of 19 Floors
554           6th   of 15 Floors
555          16th   of 19 Floors
556           8th   of 16 Floors
557          12nd   of 15 Floors
558          12nd   of 18 Floors
559           5th   of 22 Floors
560           9th   of 42 Floors
561           7th   of 14 Floors
562           7th   of 12 Floors
563           7th   of 12 Floors
564           5th   of 16 Floors
565           8th   of 31 Floors
566           7th   of 21 Floors
567           5th   of 29 Floors
568           9th   of 30 Floors
569          11st   of 29 Floors
570          10th   of 19 Floors
571           6th   of 31 Floors
572            3rd   of 9 Floors
573          22nd   of 30 Floors
574           5th   of 20 Floors
575          15th   of 29 Floors
576           5th   of 14 Floors
577          Ground of 14 Floors
578           6th   of 14 Floors
579           1st   of 24 Floors
580            2nd   of 8 Floors
581          12nd   of 19 Floors
582          12nd   of 25 Floors
583           6th   of 17 Floors
584           8th   of 18 Floors
585            4th   of 5 Floors
586           5th   of 25 Floors
587           2nd   of 19 Floors
588          20th   of 30 Floors
589          12nd   of 14 Floors
590          18th   of 19 Floors
591           2nd   of 26 Floors
592           3rd   of 15 Floors
593           3rd   of 19 Floors
594          18th   of 51 Floors
595           7th   of 27 Floors
596          17th   of 19 Floors
597           8th   of 14 Floors
598           2nd   of 19 Floors
599           8th   of 19 Floors
600           9th   of 30 Floors
601           3rd   of 18 Floors
602          12nd   of 23 Floors
603          10th   of 28 Floors
604            2nd   of 5 Floors
605          Ground of 21 Floors
606           7th   of 16 Floors
607            2nd   of 9 Floors
608            5th   of 9 Floors

In [88]:
df['floorNum'].isnull().sum()

2

In [89]:
df[df['floorNum'].isnull()]

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
181,3 BHK Flat in Dwarka Expressway Gurgaon,experion heartsong,1.08,6150.0,Built Up area: 1758 (163.32 sq.m.),3,3,0,not available,"604, Tower B-3, 6th Floor,Sector 108, Dwarka E...",NaN,NaN,Under Construction,NaN,A property by one of the most reputed builders...,[],NaN,NaN
2767,2 BHK Flat in Sector 78 Gurgaon,nan,0.60,3692.0,Built Up area: 1625 (150.97 sq.m.),2,2,0,not available,"Gurgaon, Sector 78 Gurgaon, Gurgaon, Haryana",NaN,NaN,Under Construction,NaN,The property is under construction it's by rah...,[],NaN,"['Safety4 out of 5', 'Lifestyle4 out of 5', 'E..."

In [93]:
df['floorNum'] = df['floorNum'].str.split(' ').str.get(0).replace('Ground','0').str.replace('Basement','-1').str.replace('Lower','0').str.extract(r'(\d+)')

In [94]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2,2,1,not available,"Krishna Colony, Gurgaon, Haryana",4,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692.0,Carpet area: 650 (60.39 sq.m.),2,2,1,not available,"46b, Ashok Vihar, Gurgaon, Haryana",1,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,6722.0,Carpet area: 595 (55.28 sq.m.),2,2,3,not available,"Sohna, Gurgaon, Haryana",12,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,12250.0,Carpet area: 1200 (111.48 sq.m.),2,2,2,study room,"Sector 61 Gurgaon, Gurgaon, Haryana",2,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,5204.0,Super Built up area 1345(124.95 sq.m.),2,2,3,study room,"Sector 92 Gurgaon, Gurgaon, Haryana",5,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [95]:
df['facing'].value_counts()

facing
North-East    505
East          489
North         301
South         203
West          183
North-West    162
South-East    144
South-West    135
Name: count, dtype: int64

In [96]:
df['facing'].isnull().sum()

874

In [97]:
df['facing'].fillna('NA', inplace=True)

In [98]:
df['facing'].value_counts()

facing
NA            874
North-East    505
East          489
North         301
South         203
West          183
North-West    162
South-East    144
South-West    135
Name: count, dtype: int64

In [99]:
df.insert(loc=4,column='area',value=round((df['price']*10000000)/df['price_per_sqft']))

In [100]:
df.insert(loc=1,column='property_type',value='flat')

In [101]:
df.head()

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,flat,maa bhagwati residency,0.45,5000.0,900.0,Carpet area: 900 (83.61 sq.m.),2,2,1,not available,"Krishna Colony, Gurgaon, Haryana",4,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,flat,apna enclave,0.50,7692.0,650.0,Carpet area: 650 (60.39 sq.m.),2,2,1,not available,"46b, Ashok Vihar, Gurgaon, Haryana",1,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,flat,tulsiani easy in homes,0.40,6722.0,595.0,Carpet area: 595 (55.28 sq.m.),2,2,3,not available,"Sohna, Gurgaon, Haryana",12,NA,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,flat,smart world orchard,1.47,12250.0,1200.0,Carpet area: 1200 (111.48 sq.m.),2,2,2,study room,"Sector 61 Gurgaon, Gurgaon, Haryana",2,NA,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,flat,parkwood westend,0.70,5204.0,1345.0,Super Built up area 1345(124.95 sq.m.),2,2,3,study room,"Sector 92 Gurgaon, Gurgaon, Haryana",5,NA,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [102]:
df.shape

(2996, 20)

In [103]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2996 entries, 0 to 3027
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    2996 non-null   object
 1   property_type    2996 non-null   object
 2   society          2996 non-null   object
 3   price            2996 non-null   float64
 4   price_per_sqft   2996 non-null   float64
 5   area             2996 non-null   float64
 6   areaWithType     2996 non-null   object
 7   bedRoom          2996 non-null   int64
 8   bathroom         2996 non-null   int64
 9   balcony          2996 non-null   object
 10  additionalRoom   2996 non-null   object
 11  address          2990 non-null   object
 12  floorNum         2994 non-null   object
 13  facing           2996 non-null   object
 14  agePossession    2995 non-null   object
 15  nearbyLocations  2905 non-null   object
 16  description      2996 non-null   object
 17  furnishDetails   2200 non-null   object
 18  features         2589 non-null   object
 19  rating           2668 non-null   object
dtypes: float64(3), int64(2), object(15)
memory usage: 556.1+ KB

In [104]:
df.to_csv('flats_cleaned.csv',index=False)