In [1]:
import numpy as np
import pandas as pd

In [2]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [3]:
df = pd.read_csv('gurgaon_properties.csv')

In [4]:
df.sample(5)

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
97,2 BHK Flat in Sector 88A Gurgaon,flat,godrej oasis,1.15,7116.0,1616.0,Super Built up area 1616(150.13 sq.m.)Carpet a...,2,2,3,"study room,pooja room","Dwarka Expressway, Sector 88A Gurgaon, Gurgaon...",14.0,South-East,1 to 5 Year Old,"['Double Infinity market', 'Pataudi road', 'Dw...",Available very spacious 2 bhk plus study flat....,"['4 Fan', '4 Light', '3 AC', '1 Modular Kitche...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction4.5 out ..."
752,7 Bedroom House for sale in Lucknow,house,dlf garden city floors,4.00,17817.0,2245.0,Plot area 2245(208.57 sq.m.),7,7,3+,not available,"Lucknow, Gurgaon, Haryana",4.0,NaN,0 to 1 Year Old,"['Sapphire 83 Mall', 'Dwarka Expressway', 'NH-...",I have a house/villa available for sale in dlf...,[],"['Feng Shui / Vaastu Compliant', 'Private Gard...",NaN
876,1 BHK Flat in Sohna,flat,hcbs sports ville,0.22,3142.0,700.0,Carpet area: 700 (65.03 sq.m.),1,1,1,not available,"Sohna, Gurgaon, Haryana",1.0,NaN,0 to 1 Year Old,"['The roadside cafe', 'GD Goenka Mess', 'ROyal...",Located right beside sohna road and k r mangal...,"['1 Bed', '2 Fan', '1 Sofa', '3 Light', '1 Mod...","['Security / Fire Alarm', 'Power Back-up', 'In...","['Green Area4 out of 5', 'Construction4 out of..."
1215,3 BHK Flat in Sector 65 Gurgaon,flat,m3m golfestate,5.00,18518.0,2700.0,Super Built up area 2979(276.76 sq.m.)Built Up...,3,3,3+,"pooja room,servant room","2809, Sector 65 Gurgaon, Gurgaon, Haryana",28.0,North-East,1 to 5 Year Old,"['Sector 54 Chowk Metro Station', 'Sahara Mall...","Situated in sector 65 gurgaon, m3m golfestate ...","['3 Wardrobe', '6 Fan', '1 Exhaust Fan', '4 Ge...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction5 out of..."
689,3 BHK Flat in Sector 66 Gurgaon,flat,emaar mgf the enclave,1.90,10555.0,1800.0,Super Built up area 1920(178.37 sq.m.)Built Up...,3,4,2,servant room,"1003, Sector 66 Gurgaon, Gurgaon, Haryana",8.0,North-East,1 to 5 Year Old,"['Emaar Colonnade', 'M3M Cosmopolitan', 'Elan ...",This beautiful 3 bhk flat in sector 66 gurgaon...,"['3 Wardrobe', '5 Fan', '1 Exhaust Fan', '3 Ge...","['Centrally Air Conditioned', 'Water purifier'...","['Environment3 out of 5', 'Lifestyle4 out of 5..."

In [5]:
df.sample(5)

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
371,19 Bedroom House for sale in Sector 17A Gurgaon,house,independent,3.87,5160.0,7500.0,Plot area 1623(150.78 sq.m.)Built Up area: 750...,19,17,3+,"study room,store room","690, Sector 17A Gurgaon, Gurgaon, Haryana",5.0,North-West,1 to 5 Year Old,"['Iffco chowk metro station', 'Citi bank ATM',...",The building is equipped with modern fittings....,NaN,"['False Ceiling Lighting', 'Water Storage', 'N...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
1530,2 BHK Flat in Sector 102 Gurgaon,flat,shapoorji pallonji joyville gurugram,1.24,10205.0,1215.0,Super Built up area 1215(112.88 sq.m.),2,2,2,not available,"N/a, Sector 102 Gurgaon, Gurgaon, Haryana",10.0,East,1 to 5 Year Old,"['Khan Market', 'The Esplanade Mall', 'Dwarka ...",This 2 bhk flat is located in shapoorji pallon...,NaN,"['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area4 out of 5', 'Construction5 out of..."
1988,3 BHK Flat in Sector 71 Gurgaon,flat,chd avenue,1.25,6597.0,1895.0,Super Built up area 1743(161.93 sq.m.),3,4,2,"pooja room,study room,servant room,others","T4-1404, Sector 71 Gurgaon, Gurgaon, Haryana",14.0,North-East,1 to 5 Year Old,"['Huda City Centre', 'Apna Mart', 'Rajiv Chowk...",Looking for a 3 bhk property for sale in gurga...,"['7 Fan', '1 Fridge', '1 Exhaust Fan', '3 Geys...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area5 out of 5', 'Construction3 out of..."
3032,2 BHK Flat in Sector 68 Gurgaon,flat,supertech hues,0.93,8611.0,1080.0,Carpet area: 1080 (100.34 sq.m.),2,2,2,not available,"Sector 68, Sector 68 Gurgaon, Gurgaon, Haryana",11.0,NaN,undefined,NaN,Best in class property available at sector 68 ...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment4 out of 5', 'Safety5 out of 5', ..."
3924,5 Bedroom House for sale in Sector 66 Gurgaon,house,emaar mgf marbella,11.00,33951.0,3240.0,Plot area 360(301.01 sq.m.),5,6,3+,"pooja room,study room,servant room,store room","Emaar Mgf Marbella, Sector 66, Gurugram, Secto...",2.0,North-East,0 to 1 Year Old,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...",360 sq yards duplex villa available for sale i...,"['4 Wardrobe', '7 Fan', '1 Fridge', '1 Exhaust...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment3 out of 5', 'Safety4 out of 5', ..."

In [6]:
df.shape

(3960, 20)

In [7]:
df.duplicated().sum()

0

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3960 entries, 0 to 3959
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    3960 non-null   object
 1   property_type    3960 non-null   object
 2   society          3959 non-null   object
 3   price            3941 non-null   float64
 4   price_per_sqft   3941 non-null   float64
 5   area             3941 non-null   float64
 6   areaWithType     3960 non-null   object
 7   bedRoom          3960 non-null   int64
 8   bathroom         3960 non-null   int64
 9   balcony          3960 non-null   object
 10  additionalRoom   3960 non-null   object
 11  address          3949 non-null   object
 12  floorNum         3939 non-null   float64
 13  facing           2783 non-null   object
 14  agePossession    3959 non-null   object
 15  nearbyLocations  3753 non-null   object
 16  description      3960 non-null   object
 17  furnishDetails   2929 non-null   object
 18  features         3251 non-null   object
 19  rating           3511 non-null   object
dtypes: float64(4), int64(2), object(14)
memory usage: 618.9+ KB

In [9]:
df.isnull().sum()

property_name         0
property_type         0
society               1
price                19
price_per_sqft       19
area                 19
areaWithType          0
bedRoom               0
bathroom              0
balcony               0
additionalRoom        0
address              11
floorNum             21
facing             1177
agePossession         1
nearbyLocations     207
description           0
furnishDetails     1031
features            709
rating              449
dtype: int64

In [10]:
df.head()

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,1 BHK Flat in Sector 71 Gurgaon,flat,signature andour heights,0.39,9846.0,396.0,Super Built up area 325(30.19 sq.m.),1,1,2,not available,"Sector 71 Gurgaon, Gurgaon, Haryana",1.0,NaN,0 to 1 Year Old,"['Bigbasket SPR 5K DS', 'iON Digital Zone, DPG...",Signature andour heights is one of the most po...,[],NaN,"['Management4 out of 5', 'Green Area5 out of 5..."
1,2 Bedroom House for sale in Laxman Vihar,house,independent,0.55,6813.0,807.0,Built Up area: 75,2,1,1,not available,"Laxman Vihar, Gurgaon, Haryana",1.0,NaN,5 to 10 Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...",We are proud owners of house/villa available f...,"['3 Fan', '1 Exhaust Fan', '6 Light', 'No AC',...",NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
2,4 Bedroom House for sale in Sector 1 Gurgaon,house,independent,1.85,16003.0,1156.0,Carpet area: 1156 (107.4 sq.m.),4,3,2,not available,"975 Friends Colony, Sector 1 Gurgaon, Gurgaon,...",3.0,NaN,undefined,NaN,4bhk residential house for resale in sector 1 ...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,NaN
3,2 BHK Flat in Sector 81 Gurgaon,flat,signature global city 81,0.82,8639.0,949.0,Built Up area: 955 (88.72 sq.m.)Carpet area: 5...,2,2,3,not available,"Sector 81, Sector 81 Gurgaon, Gurgaon, Haryana",2.0,East,undefined,"['Orris Community Center', 'HP Petrol Pump', '...",Best in class property available at sector 81 ...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment4.5 out of 5', 'Lifestyle4 out of..."
4,4 Bedroom House for sale in Sector 28 Gurgaon,house,suncity essel towers,6.00,22222.0,2700.0,Plot area 300(250.84 sq.m.),4,4,3+,study room,"Sector 28 Gurgaon, Gurgaon, Haryana",3.0,East,10+ Year Old,"['Iffco chowk metro station', 'Mg road metro s...",5bhk spacious independent villa for sale in co...,"['5 Wardrobe', '10 Fan', '10 Light', '1 Modula...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."

In [13]:
df['property_name'].str.split('in').str.get(1).str.replace('Gurgaon', '')

0                                              Sector 71
1                                            Laxman Vihar
2                                               Sector 1
3                                              Sector 81
4                                              Sector 28
5                                              Sector 26
6                                              Sector 67
7                                              Sector 70
8                                            Sector 89 A
9                                              Sector 33
10                                             Sector 92
11                                            DLF Phase 1
12                                             Sector 83
13                          Ashok Vihar Phase 3 Extension
14                                            Sector 17B
15                                             Prem Nagar
16                                             Sector 69
17                                             Sector 84
18                                            Sector 105
19                               G block DLF City Phase 1
20                                            Sector 111
21                                             Sector 65
22                                             Sector 14
23                                                  Sohna
24                                             Sector 14
25                                            Sector 37C
26                                             Sector 85
27                                             Sector 49
28                                               Samaspur
29                                            Sector 88A
30                                             Sector 70
31                                            Sector 104
32                                             Sector 11
33                                            Sector 107
34                               Anand Garden, Sector-105
35                                            Sector 37D
36                                             Sector 61
37                                                  Sohna
38                                             Sector 83
39                                             Sector 65
40                                             Sector 22
41                                             Sector 33
42                                             Sector 38
43                                             Sector 77
44                                             Sector 65
45                                            Sector 113
46                                             Sector 76
47                                             Sector 52
48                                             Sector 40
49                                              Sector 3
50                                              Sector 4
51                                            Sector 103
52                                              Jacobpura
53                                                  Sohna
54                                            Sector 108
55                                              Sector 3
56                                            Sector 109
57                                             Sector 68
58                                             Sector 92
59                                             Sector 56
60                                             Sector 30
61                                          Vishnu Garden
62                                            Sector 113
63                                             Sector 60
64                                            Sector 111
65                                        Sector-33 Sohna
66                                            Sector 112
67                                             Sector 56
68                                                  Sohna
69                                             Sector 49
70                                             Sector 95
71                                            Sector 102
72                                            Sector 88B
73                                            Sector 102
74                                            Sector 108
75                                            Sector 99A
76                                            Sector 107
77                                             Sector 69
78                                        Nirvana Country
79                                             Sector 78
80                                             Sector 90
81                                            DLF Phase 1
82                                            Sector 88A
83                                             Sector 85
84                                            Sector 108
85                                             Sector 72
86                                            Sector 112
87                                            Sector 104
88                                            Malibu Town
89                                                  Sohna
90                                             Sector 65
91                                            Palam Vihar
92                                             Sector 79
93                                             Sector 62
94                                             Sector 85
95                                             Sector 48
96                                     Dwarka Expressway
97                                            Sector 88A
98                                            Ashok Vihar
99                                             Sector 86
100                                                 Sohna
101                                               Suncity
102                                           Sector 99A
103                                          Laxman Vihar
104                                           Sector 103
105                                            Sector 95
106                                            Sector 89
107                                         Rattan Garden
108                                           Sector 102
109                                            Sector 81
110                                           Sector 103
111                                           Sector 82A
112                                           Sector 70A
113                                            Sector 65
114                                            Sector 82
115                                            Sector 65
116                                           DLF Phase 3
117                                                 Sohna
118                                      Golf Course Road
119                                           Sector 82A
120                                            Sector 79
121                                            Sector 89
122                                            Sector 26
123                                                 Sohna
124                                           Sector 95A
125                                           DLF Phase 5
126                                            Sector 56
127                                            Sector 99
128                                           DLF Phase 4
129                                                  BPTP
130                                           Sector 37C
131                                            Sector 85
132                                            Sector 89
133                                           DLF Phase 2
134                                           Sector 103
135                                            Sector 71
136                                                 Sohna
137                                           Sector 113
138                                            Sector 92
139                                            Bhim Nagar
140                                        Krishna Colony
141                                   Ansal's Palam Vihar
142                                            Sector 70
143                                               Manesar
144                                            Sector 50
145                                           Sector 37C
146                                           Sector 113
147                                            Sector 83
148                                                 Sohna
149                                            Sector 78
150                                            Sector 69
151                                            Sector 66
152                                            Sector 92
153                                           Sector 109
154                                            Sector 82
155                                            Sector 61
156                                           DLF Phase 1
157                                            Sector 81
158                                            Sector 28
159                                           Sector 70A
160                                            Sector 81
161                                            Sector 47
162                                       Nirvana Country
163                                            Sector 52
164                               New Palam Vihar Phase 1
165                                           Sector 104
166                                   Ashok Vihar Phase I
167                                           Sector 102
168                                            Sector 69
169                                            Sector 82
170                                            Sector 82
171                                            Sector 69
172                                            Sector 83
173                                            Sector 92
174                                        Krishna Colony
175                                          Sector 89 A
176                                            Sector 70
177                                           Sector 110
178                                         Garauli Kalan
179                                            Sector 81
180                                            Sector 95
181                                            Sector 81
182                           B Block Sushant Lok Phase 1
183                                           Palam Vihar
184                                           Sector 108
185                                   Sushant Lok Phase 3
186                                           Sector 109
187                                           Palam Vihar
188                                           Sector 70A
189                                            Sector 83
190                                            Sector 85
191                                           Palam Vihar
192                                            Sector 40
193                                           Sector 37D
194                                                 Sohna
195                                            Sector 48
196                                       Sector-33 Sohna
197                                       Sector 36 Sohna
198                                            Sector 84
199                                            Sector 56
200                                           Sector 102
201                                            Sector 83
202                                            Bhim Nagar
203                                                 Sohna
204                                            Sector 95
205                                            Sector 70
206                                            Sector 92
207                                 laxmna vihar, phase 2
208                                            Sector 77
209                                             Sector 9
210                                            Sector 95
211                                                 Sohna
212                                           Sector 109
213                                            Sector 91
214                                       Sector 36 Sohna
215                                             Sector 4
216                                           Sector 37D
217                                           Sector 109
218                                           Sector 109
219                                           IMT Manesar
220                                            Sector 82
221                                            Jyoti Park
222                                            Sector 79
223                                            Sector 65
224                                            Sector 48
225                                          Laxman Vihar
226                                           Sector 108
227                                           Sector 99A
228                                            Sector 83
229                                            Sector 90
230                                       Nirvana Country
231                                            Sector 84
232                                            Sector 61
233                                            Sector 92
234                                        Mehrauli  Road
235                                           Sector 104
236                                            Sector 59
237                                           Sector 37D
238                                            Sector 65
239                                           DLF Phase 3
240                                            Sector 84
241                                            Sector 69
242                                                 Sohna
243                                            Sector 70
244                                           Sector 63A
245                                           Sector 108
246                                            Sector 67
247                                           DLF Phase 4
248                                           Sector 109
249                                            Sector 68
250                                           Sector 109
251                                            Sector 14
252                                           Sector 37D
253                                           Sector 111
254                                           DLF Phase 3
255                                          Laxman Vihar
256                                           DLF Phase 5
257                                            Sector 69
258                                           Palam Vihar
259                                           Sector 112
260                                           Sector 112
261                                            Sector 65
262                                            Sector 60
263                                           Sector 102
264                                       Uppals Southend
265                                        Devilal Colony
266                                           Ashok Vihar
267                                            Sector 9A
268                                           Sector 113
269                                   Udyog Vihar Phase 1
270                                           Sector 37D
271                                           Sector 70A
272                                            Sector 65
273                                            Sector 57
274                                                 Sohna
275                                                 Sohna
276                                            Sector 79
277                                           Sector 106
278                                       Uppals Southend
279                                           Sector 113
280                                             Madanpuri
281                                           Sector 104
282                                                 Sohna
283                                            Sector 67
284                                           Palam Vihar
285                                           Sector 109
286                                           DLF Phase 1
287                                           Sector 37D
288                                       Nirvana Country
289                                           Sector 104
290                                            Sector 81
291                                           Sector 109
292                                            Sector 77
293                                            Sector 69
294                                           Malibu Town
295                                            Sector 65
296                                           Sector 102
297                                            Sector 60
298                                           Sector 103
299                                            Sector 79
300                                         Surat Nagar 1
301                                           Sector 113
302                                           Sector 67A
303                                            Sector 60
304                                            Sector 83
305                                            Sector 62
306                                            Sector 14
307                                            Sector 61
308                                                 Sohna
309                                            Sector 90
310                                           Palam Vihar
311                                            Sector 74
312                                   Sushant Lok Phase 3
313                                            Bhim Nagar
314                                 Palam Vihar Extension
315                                  Sector 1 Imt Manesar
316                                            Sector 66
317                                            Sohna Road
318                                           Sector 109
319                                           Sector 102
320                                           Sector 109
321                                           Sector 37D
322                                            Sector 81
323                                            Sector 3A
324                                            Sector 61
325                                           Sector 70A
326                                             Sector 1
327                                        Tekchand Nagar
328                                           Ansal Plaza
329                                           DLF Phase 1
330                                 Palam Vihar Extension
331                                            Sector 90
332                                             Jacobpura
333                                            Sector 85
334                                          Gandhi Nagar
335                                                 Sohna
336                                           Sector 37D
337                                            Sector 74
338                                           DLF Phase 2
339                                           Sector 108
340                                            Sector 66
341                                           Sector 110
342                                           Sector 102
343                                            Sector 52
344                                  Sector 1 Imt Manesar
345                                           DLF Phase 1
346                                           Gwal Pahari
347                                            Sector 92
348                                            Sector 22

In [14]:
df.insert(loc=3,column='sector',value=df['property_name'].str.split('in').str.get(1).str.replace('Gurgaon','').str.strip())

In [15]:
df.head()

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,1 BHK Flat in Sector 71 Gurgaon,flat,signature andour heights,Sector 71,0.39,9846.0,396.0,Super Built up area 325(30.19 sq.m.),1,1,2,not available,"Sector 71 Gurgaon, Gurgaon, Haryana",1.0,NaN,0 to 1 Year Old,"['Bigbasket SPR 5K DS', 'iON Digital Zone, DPG...",Signature andour heights is one of the most po...,[],NaN,"['Management4 out of 5', 'Green Area5 out of 5..."
1,2 Bedroom House for sale in Laxman Vihar,house,independent,Laxman Vihar,0.55,6813.0,807.0,Built Up area: 75,2,1,1,not available,"Laxman Vihar, Gurgaon, Haryana",1.0,NaN,5 to 10 Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...",We are proud owners of house/villa available f...,"['3 Fan', '1 Exhaust Fan', '6 Light', 'No AC',...",NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
2,4 Bedroom House for sale in Sector 1 Gurgaon,house,independent,Sector 1,1.85,16003.0,1156.0,Carpet area: 1156 (107.4 sq.m.),4,3,2,not available,"975 Friends Colony, Sector 1 Gurgaon, Gurgaon,...",3.0,NaN,undefined,NaN,4bhk residential house for resale in sector 1 ...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,NaN
3,2 BHK Flat in Sector 81 Gurgaon,flat,signature global city 81,Sector 81,0.82,8639.0,949.0,Built Up area: 955 (88.72 sq.m.)Carpet area: 5...,2,2,3,not available,"Sector 81, Sector 81 Gurgaon, Gurgaon, Haryana",2.0,East,undefined,"['Orris Community Center', 'HP Petrol Pump', '...",Best in class property available at sector 81 ...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment4.5 out of 5', 'Lifestyle4 out of..."
4,4 Bedroom House for sale in Sector 28 Gurgaon,house,suncity essel towers,Sector 28,6.00,22222.0,2700.0,Plot area 300(250.84 sq.m.),4,4,3+,study room,"Sector 28 Gurgaon, Gurgaon, Haryana",3.0,East,10+ Year Old,"['Iffco chowk metro station', 'Mg road metro s...",5bhk spacious independent villa for sale in co...,"['5 Wardrobe', '10 Fan', '10 Light', '1 Modula...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."

In [17]:
df['sector'] = df['sector'].str.lower()

In [18]:
df['sector'].value_counts()

sector
sohna                                                        163
sector 102                                                   113
sector 85                                                    110
sector 92                                                    104
sector 69                                                     94
sector 81                                                     90
sector 65                                                     90
sector 90                                                     90
sector 109                                                    88
sector 79                                                     80
sector 83                                                     69
sector 37d                                                    68
sector 86                                                     67
sector 104                                                    66
sector 107                                                    60
sector 108                                                    59
sector 95                                                     57
sector 56                                                     57
sector 89                                                     56
sector 48                                                     56
sector 70a                                                    54
sector 70                                                     53
sector 37c                                                    53
nirvana country                                               53
sector 84                                                     51
sector-33 sohna                                               51
palam vihar                                                   50
sector 67                                                     48
sector 66                                                     46
sector 103                                                    45
dlf phase 1                                                   43
dlf phase 2                                                   43
sector 113                                                    43
sector 82                                                     42
sector 61                                                     42
sector 106                                                    38
sector 49                                                     36
sector 99a                                                    32
sushant lok phase 1                                           31
sector 68                                                     30
sector 72                                                     29
sector 77                                                     29
sector 54                                                     27
sector 71                                                     27
laxman vihar                                                  27
dlf phase 4                                                   26
sector 112                                                    24
sector 33                                                     23
sector 88a                                                    23
dlf phase 3                                                   22
sector 111                                                    22
sector 67a                                                    22
sector 82a                                                    20
sector 22                                                     20
sector 78                                                     19
sector 63a                                                    18
sector 74                                                     18
sector 62                                                     17
sector 91                                                     17
sushant lok phase 3                                           16
sector 99                                                     16
sector 110                                                    16
sector 63                                                     15
sector 60                                                     15
sector 14                                                     15
sector 1 imt manesar                                          14
dlf phase 5                                                   14
sector 53                                                     14
rajendra park                                                 14
gwal pahari                                                   14
sector 76                                                     14
sector 52                                                     14
sector 3                                                      14
sector 36a                                                    13
sector 46                                                     13
laxman vihar phase 2                                          13
sector 39                                                     12
uppals southend                                               12
sector 38                                                     12
sector 50                                                     12
sector 31                                                     12
sohna road                                                    12
sector 47                                                     11
sector 93                                                     11
ashok vihar phase 3 extension                                 11
sector 9a                                                     11
sector 7                                                      10
sector 1a imt manesar                                         10
sector 4                                                       9
sector 95a                                                     9
south city 1                                                   9
ashok vihar phase 2                                            9
sector 55                                                      9
sector 89 a                                                    8
malibu town                                                    8
sector 57                                                      8
sector 40                                                      8
sector 10a                                                     8
sector 59                                                      8
mehrauli  road                                                 8
dwarka expressway                                              8
palam vihar extension                                          8
sector 43                                                      8
c block sushant lok phase 1                                    8
mianwali colony                                                7
sector 36 sohna                                                7
sector 58                                                      7
surat nagar 1                                                  7
sector 11                                                      7
sector 51                                                      7
new colony                                                     7
sector 26                                                      7
sector 1                                                       6
jacobpura                                                      6
jyoti park                                                     6
ashok vihar                                                    6
sector 5                                                       6
rajiv nagar                                                    6
dayanand colony                                                5
arjun nagar                                                    5
sector 105                                                     5
sector 28                                                      5
subhash nagar                                                  5
chakkarpur                                                     5
greenwood city                                                 5
sector 2                                                       5
new palam vihar                                                5
sushant lok phase 2                                            5
manesar                                                        5
saraswati vihar                                                5
ansal plaza                                                    5
sector 30                                                      5
sector 23a                                                     5
sector 80                                                      5
sector 9                                                       5
valley view estate                                             4
sector 12                                                      4
bhondsi                                                        4
sector 17                                                      4
shivaji nagar                                                  4
sector 6                                                       4
sector 36                                                      4
baldev nagar                                                   4
ravi nagar                                                     4
adarsh nagar                                                   4
shivpuri                                                       4
new                                                            4
dharam colony                                                  4
krishna colony                                                 4
sector 3a                                                      4
madanpuri                                                      4
surya vihar                                                    4
suncity                                                        4
sector 45                                                      4
sector 12a                                                     4
garhi harsaru                                                  4
vishnu garden                                                  4
devilal colony                                                 4
imt manesar                                                    4
bhim nagar                                                     4
sector 8                                                       3
sector 73                                                      3
mg road                                                        3
sector 15                                                      3
a block sushant lok phase 1                                    3
b block sushant lok phase 1                                    3
laxmi garden                                                   3
maruti kunj                                                    3
gandhi nagar                                                   3
sector 23                                                      3
shakti nagar                                                   3
sector 17a                                                     3
sector 110 a                                                   3
prem nagar                                                     3
sector 27                                                      3
patel nagar                                                    3
sector 17b                                                     3
sector 88b                                                     3
bissar                                                         2
pratap nagar                                                   2
block a surya vihar                                            2
sector 15 part 2                                               2
farukhnagar                                                    2
mayfield garden                                                2
sector 15 part 1                                               2
rosewood                                                       2
sector-2 sohna                                                 2
sector 24                                                      2
ambience island                                                2
shanti nagar                                                   2
rajiv chowk                                                    2
west rajiv nagar                                               2
new basti                                                      2
sohna  road                                                    2
daulatabad                                                     2
faridabad road                                                 2
sheetla colony                                                 2
iffco chowk                                                    2
bhawani enclave                                                2
sector 32                                                      2
sushant lok                                                    2
golf course ext road                                           2
golf course road                                               2
sispal vihar                                                   2
sector 41                                                      2
nars                                                           2
sector 21                                                      2
mohan nagar                                                    2
hira nagar                                                     2
acharya puri                                                   2
surat nagar phase 2                                            2
lajpat nagar                                                   2
, delhi ncr                                                    2
samaspur                                                       2
new palam vihar phase 1                                        2
shankar vihar                                                  2
manohar nagar                                                  2
sector-11 sohna                                                2
new palam vihar phase 2                                        2
surat nagar                                                    2
saraswati enclave                                              1
v block dlf phase 3                                            1
godrej aria , sector 79 ,                                      1
khandsa                                                        1
civil l                                                        1
block h ashok vihar phase iii extension                        1
sai kunj                                                       1
g block dlf city phase 1                                       1
sector 5 chowk                                                 1
gopal nagar, garhi ghasita, sonipat                            1
bptp                                                           1
jacobpura near sadar bazar                                     1
huda saraswati vihar                                           1
rajiv colony                                                   1
naharpur rupa                                                  1
mahavir pura                                                   1
mahalaxmi garden, rajendra place                               1
heritage city                                                  1
begampur khatola                                               1
sector 37a                                                     1
sector-35 sohna                                                1
near euro                                                      1
damdma                                                         1
vir nagar                                                      1
sector-5 sheetla colony                                        1
ram nagar                                                      1
bhimgarh kheri phase 3                                         1
ravi nager basai road                                          1
anand garden, sector-105                                       1
hno 13 sagar enclave sura                                      1
shivji park colony                                             1
om nagar                                                       1
ansal's palam vihar                                            1
sector-5 sohna                                                 1
kanahi                                                         1
cyber city                                                     1
rattan garden                                                  1
sec 3 bhim vihar part 1 bhimgher kheri                         1
nirvana country pocket h                                       1
sultanpur                                                      1
south city                                                     1
part 3 sector 5                                                1
old delhi road, opp sector-14                                  1
sector 4 urban estate                                          1
sector-7 hous                                                  1
near khandsa road                                              1
lucknow                                                        1
dhankot                                                        1
devi lal colony gali no 12 gurgaon nr omkar public school      1
park view                                                      1
urban estate, sector 5                                         1
carterpuri village                                             1
sector 37b                                                     1
bhora kalan                                                    1
block g sector-57                                              1
new colony, sector 7                                           1
near pataudi chowk                                             1
hsiidc plot sector 1 imt manesar                               1
ashok vihar phase 3                                            1
jat colony,fazilpur/taj nagar road                             1
b1 block sector 57                                             1
ashok vihar phase i                                            1
sector 17c                                                     1
sector 13                                                      1
garauli kalan                                                  1
laxmna vihar, phase 2                                          1
udyog vihar phase 1                                            1
near sector 1 market                                           1
tekchand nagar                                                 1
sector 9b                                                      1
sector 42                                                      1
alipur                                                         1
sadar bazar                                                    1
laxman vihar, railway road,                                    1
saroop garden rajendra park                                    1
ats marigold                                                   1
kheri                                                          1
near nand hospital                                             1
sector 21a faridabad                                           1
new jyoti park                                                 1
pataudi road                                                   1
Name: count, dtype: int64

In [19]:
df['sector'] = df['sector'].str.replace('dharam colony','sector 12')
df['sector'] = df['sector'].str.replace('krishna colony','sector 7')
df['sector'] = df['sector'].str.replace('suncity','sector 54')
df['sector'] = df['sector'].str.replace('prem nagar','sector 13')
df['sector'] = df['sector'].str.replace('mg road','sector 28')
df['sector'] = df['sector'].str.replace('gandhi nagar','sector 28')
df['sector'] = df['sector'].str.replace('laxmi garden','sector 11')
df['sector'] = df['sector'].str.replace('shakti nagar','sector 11')

In [20]:
df['sector'] = df['sector'].str.replace('baldev nagar','sector 7')
df['sector'] = df['sector'].str.replace('shivpuri','sector 7')
df['sector'] = df['sector'].str.replace('garhi harsaru','sector 17')
df['sector'] = df['sector'].str.replace('imt manesar','manesar')
df['sector'] = df['sector'].str.replace('adarsh nagar','sector 12')
df['sector'] = df['sector'].str.replace('shivaji nagar','sector 11')
df['sector'] = df['sector'].str.replace('bhim nagar','sector 6')
df['sector'] = df['sector'].str.replace('madanpuri','sector 7')

In [21]:
df['sector'] = df['sector'].str.replace('saraswati vihar','sector 28')
df['sector'] = df['sector'].str.replace('arjun nagar','sector 8')
df['sector'] = df['sector'].str.replace('ravi nagar','sector 9')
df['sector'] = df['sector'].str.replace('vishnu garden','sector 105')
df['sector'] = df['sector'].str.replace('bhondsi','sector 11')
df['sector'] = df['sector'].str.replace('surya vihar','sector 21')
df['sector'] = df['sector'].str.replace('devilal colony','sector 9')
df['sector'] = df['sector'].str.replace('valley view estate','gwal pahari')

In [22]:
df['sector'] = df['sector'].str.replace('mehrauli  road','sector 14')
df['sector'] = df['sector'].str.replace('jyoti park','sector 7')
df['sector'] = df['sector'].str.replace('ansal plaza','sector 23')
df['sector'] = df['sector'].str.replace('dayanand colony','sector 6')
df['sector'] = df['sector'].str.replace('sushant lok phase 2','sector 55')
df['sector'] = df['sector'].str.replace('chakkarpur','sector 28')
df['sector'] = df['sector'].str.replace('greenwood city','sector 45')
df['sector'] = df['sector'].str.replace('subhash nagar','sector 12')

In [23]:
df['sector'] = df['sector'].str.replace('sohna road road','sohna road')
df['sector'] = df['sector'].str.replace('malibu town','sector 47')
df['sector'] = df['sector'].str.replace('surat nagar 1','sector 104')
df['sector'] = df['sector'].str.replace('new colony','sector 7')
df['sector'] = df['sector'].str.replace('mianwali colony','sector 12')
df['sector'] = df['sector'].str.replace('jacobpura','sector 12')
df['sector'] = df['sector'].str.replace('rajiv nagar','sector 13')
df['sector'] = df['sector'].str.replace('ashok vihar','sector 3')

In [24]:
df['sector'] = df['sector'].str.replace('dlf phase 1','sector 26')
df['sector'] = df['sector'].str.replace('nirvana country','sector 50')
df['sector'] = df['sector'].str.replace('palam vihar','sector 2')
df['sector'] = df['sector'].str.replace('dlf phase 2','sector 25')
df['sector'] = df['sector'].str.replace('sushant lok phase 1','sector 43')
df['sector'] = df['sector'].str.replace('laxman vihar','sector 4')
df['sector'] = df['sector'].str.replace('dlf phase 4','sector 28')
df['sector'] = df['sector'].str.replace('dlf phase 3','sector 24')

In [25]:
df['sector'] = df['sector'].str.replace('sushant lok phase 3','sector 57')
df['sector'] = df['sector'].str.replace('dlf phase 5','sector 43')
df['sector'] = df['sector'].str.replace('rajendra park','sector 105')
df['sector'] = df['sector'].str.replace('uppals southend','sector 49')
df['sector'] = df['sector'].str.replace('sohna','sohna road')
df['sector'] = df['sector'].str.replace('ashok vihar phase 3 extension','sector 5')
df['sector'] = df['sector'].str.replace('south city 1','sector 41')
df['sector'] = df['sector'].str.replace('ashok vihar phase 2','sector 5')

In [26]:
df['sector'].value_counts()

sector
sohna road                                                   163
sector 102                                                   113
sector 85                                                    110
sector 92                                                    104
sector 69                                                     94
sector 81                                                     90
sector 65                                                     90
sector 90                                                     90
sector 109                                                    88
sector 79                                                     80
sector 104                                                    73
sector 83                                                     69
sector 37d                                                    68
sector 86                                                     67
sector 50                                                     65
sector 107                                                    60
sector 108                                                    59
sector 56                                                     57
sector 95                                                     57
sector 89                                                     56
sector 48                                                     56
sector 2                                                      55
sector 70a                                                    54
sector 37c                                                    53
sector 70                                                     53
sector 43                                                     53
sector-33 sohna road                                          51
sector 84                                                     51
sector 26                                                     50
sector 49                                                     48
sector 67                                                     48
sector 28                                                     47
sector 66                                                     46
sector 103                                                    45
sector 113                                                    43
sector 25                                                     43
sector 61                                                     42
sector 82                                                     42
sector 7                                                      39
sector 106                                                    38
sector 4                                                      36
sector 99a                                                    32
sector 54                                                     31
sector 12                                                     30
sector 68                                                     30
sector 77                                                     29
sector 72                                                     29
sector 71                                                     27
sector 57                                                     24
sector 112                                                    24
sector 24                                                     24
sector 14                                                     23
sector 88a                                                    23
sector 33                                                     23
sector 105                                                    23
sector 111                                                    22
sector 67a                                                    22
sector 11                                                     21
sector 22                                                     20
sector 3                                                      20
sector 82a                                                    20
sector 78                                                     19
sector 47                                                     19
sector 74                                                     18
gwal pahari                                                   18
sector 63a                                                    18
sector 62                                                     17
sector 91                                                     17
sector 110                                                    16
sector 99                                                     16
sector 60                                                     15
sector 63                                                     15
sector 55                                                     14
sector 53                                                     14
sector 52                                                     14
sector 76                                                     14
sector 1 manesar                                              14
sector 9                                                      13
sector 6                                                      13
sector 4 phase 2                                              13
sector 46                                                     13
sector 36a                                                    13
sector 39                                                     12
sector 38                                                     12
sector 31                                                     12
sohna road road                                               12
sector 9a                                                     11
sector 93                                                     11
sector 3 phase 3 extension                                    11
sector 41                                                     11
sector 13                                                     10
sector 1a manesar                                             10
sector 45                                                      9
manesar                                                        9
sector 3 phase 2                                               9
sector 95a                                                     9
sector 8                                                       8
sector 17                                                      8
sector 23                                                      8
c block sector 43                                              8
sector 10a                                                     8
sector 2 extension                                             8
sector 59                                                      8
sector 40                                                      8
sector 89 a                                                    8
dwarka expressway                                              8
sector 58                                                      7
sector 36 sohna road                                           7
sector 51                                                      7
sector 5                                                       6
sector 1                                                       6
sector 21                                                      6
new sector 2                                                   5
sector 80                                                      5
sector 30                                                      5
sector 23a                                                     5
sector 12a                                                     4
sector 36                                                      4
new                                                            4
sector 3a                                                      4
sector 110 a                                                   3
b block sector 43                                              3
sector 73                                                      3
sector 88b                                                     3
sector 17a                                                     3
sector 17b                                                     3
a block sector 43                                              3
sector 15                                                      3
patel nagar                                                    3
sector 27                                                      3
maruti kunj                                                    3
surat nagar                                                    2
shankar vihar                                                  2
manohar nagar                                                  2
new sector 2 phase 2                                           2
sector-11 sohna road                                           2
shanti nagar                                                   2
sector-2 sohna road                                            2
mayfield garden                                                2
ambience island                                                2
sector 15 part 1                                               2
rajiv chowk                                                    2
block a sector 21                                              2
new basti                                                      2
sohna road  road                                               2
daulatabad                                                     2
iffco chowk                                                    2
sheetla colony                                                 2
faridabad road                                                 2
bissar                                                         2
rosewood                                                       2
bhawani enclave                                                2
golf course ext road                                           2
west sector 13                                                 2
surat nagar phase 2                                            2
pratap nagar                                                   2
mohan nagar                                                    2
samaspur                                                       2
nars                                                           2
acharya puri                                                   2
sushant lok                                                    2
golf course road                                               2
new sector 2 phase 1                                           2
sector 32                                                      2
hira nagar                                                     2
sispal vihar                                                   2
lajpat nagar                                                   2
farukhnagar                                                    2
sector 15 part 2                                               2
, delhi ncr                                                    2
sector-5 sheetla colony                                        1
south city                                                     1
sector 5 chowk                                                 1
near euro                                                      1
damdma                                                         1
sector-5 sohna road                                            1
mahasector 11, rajendra place                                  1
rajiv colony                                                   1
naharpur rupa                                                  1
shivji park colony                                             1
mahavir pura                                                   1
bhimgarh kheri phase 3                                         1
sector 37a                                                     1
sector 12 near sadar bazar                                     1
huda sector 28                                                 1
vir nagar                                                      1
sec 3 bhim vihar part 1 bhimgher kheri                         1
kanahi                                                         1
khandsa                                                        1
sector-35 sohna road                                           1
begampur khatola                                               1
om nagar                                                       1
hno 13 sagar enclave sura                                      1
v block sector 24                                              1
civil l                                                        1
block h sector 3 phase iii extension                           1
sai kunj                                                       1
ravi nager basai road                                          1
saraswati enclave                                              1
heritage city                                                  1
gopal nagar, garhi ghasita, sonipat                            1
godrej aria , sector 79 ,                                      1
ram nagar                                                      1
cyber city                                                     1
sector 21a faridabad                                           1
near sector 1 market                                           1
urban estate, sector 5                                         1
lucknow                                                        1
sector-7 hous                                                  1
sector 4 urban estate                                          1
old delhi road, opp sector-14                                  1
jat colony,fazilpur/taj nagar road                             1
part 3 sector 5                                                1
b1 block sector 57                                             1
alipur                                                         1
sector 42                                                      1
tekchand nagar                                                 1
udyog vihar phase 1                                            1
laxmna vihar, phase 2                                          1
garauli kalan                                                  1
sector 3 phase i                                               1
ansal's sector 2                                               1
bptp                                                           1
rattan garden                                                  1
anand garden, sector-105                                       1
g block dlf city phase 1                                       1
park view                                                      1
carterpuri village                                             1
sultanpur                                                      1
block g sector-57                                              1
sadar bazar                                                    1
sector 4, railway road,                                        1
saroop garden sector 105                                       1
ats marigold                                                   1
kheri                                                          1
near nand hospital                                             1
new sector 7                                                   1
sector 17c                                                     1
near khandsa road                                              1
dhankot                                                        1
devi lal colony gali no 12 gurgaon nr omkar public school      1
sector 37b                                                     1
bhora kalan                                                    1
sector 7, sector 7                                             1
hsiidc plot sector 1 manesar                                   1
sector 3 phase 3                                               1
sector 9b                                                      1
sector 50 pocket h                                             1
near pataudi chowk                                             1
pataudi road                                                   1
Name: count, dtype: int64

In [27]:
a = df['sector'].value_counts()[df['sector'].value_counts() >= 3]
df = df[df['sector'].isin(a.index)]

In [28]:
df['sector'].value_counts()

sector
sohna road                    163
sector 102                    113
sector 85                     110
sector 92                     104
sector 69                      94
sector 81                      90
sector 90                      90
sector 65                      90
sector 109                     88
sector 79                      80
sector 104                     73
sector 83                      69
sector 37d                     68
sector 86                      67
sector 50                      65
sector 107                     60
sector 108                     59
sector 56                      57
sector 95                      57
sector 89                      56
sector 48                      56
sector 2                       55
sector 70a                     54
sector 37c                     53
sector 43                      53
sector 70                      53
sector-33 sohna road           51
sector 84                      51
sector 26                      50
sector 49                      48
sector 67                      48
sector 28                      47
sector 66                      46
sector 103                     45
sector 113                     43
sector 25                      43
sector 61                      42
sector 82                      42
sector 7                       39
sector 106                     38
sector 4                       36
sector 99a                     32
sector 54                      31
sector 12                      30
sector 68                      30
sector 72                      29
sector 77                      29
sector 71                      27
sector 112                     24
sector 57                      24
sector 24                      24
sector 88a                     23
sector 105                     23
sector 33                      23
sector 14                      23
sector 111                     22
sector 67a                     22
sector 11                      21
sector 3                       20
sector 22                      20
sector 82a                     20
sector 78                      19
sector 47                      19
sector 63a                     18
gwal pahari                    18
sector 74                      18
sector 91                      17
sector 62                      17
sector 110                     16
sector 99                      16
sector 63                      15
sector 60                      15
sector 1 manesar               14
sector 53                      14
sector 52                      14
sector 55                      14
sector 76                      14
sector 4 phase 2               13
sector 6                       13
sector 9                       13
sector 36a                     13
sector 46                      13
sector 39                      12
sector 31                      12
sector 38                      12
sohna road road                12
sector 9a                      11
sector 3 phase 3 extension     11
sector 41                      11
sector 93                      11
sector 1a manesar              10
sector 13                      10
manesar                         9
sector 45                       9
sector 95a                      9
sector 3 phase 2                9
c block sector 43               8
sector 17                       8
sector 8                        8
sector 10a                      8
dwarka expressway               8
sector 40                       8
sector 89 a                     8
sector 23                       8
sector 59                       8
sector 2 extension              8
sector 36 sohna road            7
sector 51                       7
sector 58                       7
sector 1                        6
sector 21                       6
sector 5                        6
sector 30                       5
sector 80                       5
new sector 2                    5
sector 23a                      5
sector 36                       4
sector 3a                       4
sector 12a                      4
new                             4
patel nagar                     3
sector 27                       3
sector 17b                      3
a block sector 43               3
sector 110 a                    3
b block sector 43               3
sector 88b                      3
maruti kunj                     3
sector 73                       3
sector 15                       3
sector 17a                      3
Name: count, dtype: int64

In [29]:
df['sector'] = df['sector'].str.replace('sector 95a','sector 95')
df['sector'] = df['sector'].str.replace('sector 23a','sector 23')
df['sector'] = df['sector'].str.replace('sector 12a','sector 12')
df['sector'] = df['sector'].str.replace('sector 3a','sector 3')
df['sector'] = df['sector'].str.replace('sector 110 a','sector 110')
df['sector'] = df['sector'].str.replace('patel nagar','sector 15')
df['sector'] = df['sector'].str.replace('a block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('maruti kunj','sector 12')
df['sector'] = df['sector'].str.replace('b block sector 43','sector 43')

In [30]:
df['sector'] = df['sector'].str.replace('sector-33 sohna road','sector 33')
df['sector'] = df['sector'].str.replace('sector 1 manesar','manesar')
df['sector'] = df['sector'].str.replace('sector 4 phase 2','sector 4')
df['sector'] = df['sector'].str.replace('sector 1a manesar','manesar')
df['sector'] = df['sector'].str.replace('c block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('sector 89 a','sector 89')
df['sector'] = df['sector'].str.replace('sector 2 extension','sector 2')
df['sector'] = df['sector'].str.replace('sector 36 sohna road','sector 36')

In [31]:
df['sector'].value_counts()

sector
sohna road                    163
sector 102                    113
sector 85                     110
sector 92                     104
sector 69                      94
sector 81                      90
sector 90                      90
sector 65                      90
sector 109                     88
sector 79                      80
sector 33                      74
sector 104                     73
sector 83                      69
sector 37d                     68
sector 86                      67
sector 43                      67
sector 95                      66
sector 50                      65
sector 89                      64
sector 2                       63
sector 107                     60
sector 108                     59
sector 56                      57
sector 48                      56
sector 70a                     54
sector 37c                     53
sector 70                      53
sector 84                      51
sector 26                      50
sector 4                       49
sector 49                      48
sector 67                      48
sector 28                      47
sector 66                      46
sector 103                     45
sector 113                     43
sector 25                      43
sector 61                      42
sector 82                      42
sector 7                       39
sector 106                     38
sector 12                      37
manesar                        33
sector 99a                     32
sector 54                      31
sector 68                      30
sector 72                      29
sector 77                      29
sector 71                      27
sector 112                     24
sector 3                       24
sector 24                      24
sector 57                      24
sector 14                      23
sector 105                     23
sector 88a                     23
sector 67a                     22
sector 111                     22
sector 11                      21
sector 22                      20
sector 82a                     20
sector 78                      19
sector 47                      19
sector 110                     19
sector 74                      18
gwal pahari                    18
sector 63a                     18
sector 62                      17
sector 91                      17
sector 99                      16
sector 63                      15
sector 60                      15
sector 76                      14
sector 55                      14
sector 52                      14
sector 53                      14
sector 9                       13
sector 36a                     13
sector 6                       13
sector 46                      13
sector 23                      13
sector 31                      12
sohna road road                12
sector 38                      12
sector 39                      12
sector 3 phase 3 extension     11
sector 36                      11
sector 9a                      11
sector 41                      11
sector 93                      11
sector 13                      10
sector 45                       9
sector 3 phase 2                9
sector 10a                      8
sector 8                        8
dwarka expressway               8
sector 17                       8
sector 59                       8
sector 40                       8
sector 58                       7
sector 51                       7
sector 15                       6
sector 21                       6
sector 5                        6
sector 1                        6
new sector 2                    5
sector 30                       5
sector 80                       5
new                             4
sector 73                       3
sector 88b                      3
sector 17a                      3
sector 17b                      3
sector 27                       3
Name: count, dtype: int64

In [32]:
df[df['sector'] == 'new']

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
1315,4 BHK Flat in New Gurgaon,flat,dlf 76,new,4.00,11428.0,3500.0,Carpet area: 3500 (325.16 sq.m.),4,4,2,"study room,servant room","New Gurgaon, Gurgaon, Haryana",4.0,NaN,Jun 2027,"['Shri Balaji Hospital and Trauma Center', 'S....",This lovely 4 bhk apartment/flat in new gurgao...,"['6 Wardrobe', '1 Fridge', '8 Fan', '1 Exhaust...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...",NaN
2218,4 BHK Flat in New Gurgaon,flat,sare homes,new,0.85,4786.0,1776.0,Super Built up area 1776(165 sq.m.),4,4,3,not available,"New Gurgaon, Gurgaon, Haryana",3.0,NaN,5 to 10 Year Old,"['Columbia Asia Hospital', 'Apex Multi Special...",Located in the popular residential address of ...,[],NaN,NaN
3031,2 BHK Flat in New Gurgaon,flat,green court,new,0.38,5507.0,690.0,Carpet area: 690 (64.1 sq.m.),2,2,1,not available,"New Gurgaon, Gurgaon, Haryana",7.0,NaN,Under Construction,"['Ing bank ATM', 'Dcb bank ATM', 'Indus ind ba...",We are the proud owners of this 2 bhk apartmen...,[],"['Intercom Facility', 'Lift(s)', 'Maintenance ...",NaN
3888,2 BHK Flat in New Gurgaon,flat,takshila heights sector 37 c,new,0.67,5583.0,1200.0,Super Built up area 1200(111.48 sq.m.),2,2,2,not available,"New Gurgaon, Gurgaon, Haryana",3.0,NaN,1 to 5 Year Old,"['Shri Balaji Hospital and Trauma Center', 'S....",Check out this 2 bhk apartment for sale in tak...,[],"['Lift(s)', 'Swimming Pool', 'Visitor Parking'...",NaN

In [33]:
df.loc[955,'sector'] = 'sector 37'
df.loc[2800,'sector'] = 'sector 92'
df.loc[2838,'sector'] = 'sector 90'
df.loc[2857,'sector'] = 'sector 76'

In [34]:
df[df['sector'] == 'new sector 2']

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
442,2 Bedroom House for sale in New Palam Vihar,house,my home,new sector 2,0.34,12592.0,270.0,Plot area 270(25.08 sq.m.),2.0,2.0,2,not available,"Ez-19 A, New Palam Vihar, Gurgaon, Haryana",3.0,West,5 to 10 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",There are availability of various facilities l...,"['1 Wardrobe', '3 Fan', '6 Light', 'No AC', 'N...","['Water Storage', 'Park', 'Visitor Parking']","['Environment4 out of 5', 'Lifestyle4 out of 5..."
835,2 BHK Flat in New Palam Vihar,flat,ompee k s residency,new sector 2,1.60,26936.0,594.0,Carpet area: 66 (55.18 sq.m.),2.0,2.0,2,not available,"New Palam Vihar, Gurgaon, Haryana",1.0,NaN,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",We are the proud owners of this 2 bhk apartmen...,NaN,NaN,"['Environment4 out of 5', 'Safety4 out of 5', ..."
1843,3 Bedroom House for sale in New Palam Vihar,house,independent,new sector 2,1.00,8796.0,1137.0,Plot area 120(100.34 sq.m.)Built Up area: 120 ...,3.0,2.0,2,pooja room,"Q-148, New Palam Vihar, Phase-2, Near Royal Oa...",1.0,North,10+ Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","Ground and first floor, Ground floor: Ground f...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
2603,2 BHK Flat in New Palam Vihar,flat,my home,new sector 2,0.28,3166.0,884.0,Carpet area: 900 (83.61 sq.m.),2.0,1.0,1,others,"F 150/b, New Palam Vihar, Gurgaon, Haryana",2.0,NaN,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","2 bhk room with wooden coverd ,1 drawing room,...","['3 Wardrobe', '5 Light', '1 Chimney', '1 Modu...","['Water Storage', 'Park']","['Environment4 out of 5', 'Safety4 out of 5', ..."
3548,2 BHK Flat in New Palam Vihar,flat,my home,new sector 2,0.22,4400.0,500.0,Carpet area: 500 (46.45 sq.m.),2.0,2.0,1,not available,"New Palam Vihar, Gurgaon, Haryana",1.0,NaN,0 to 1 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",Cctv surveillance are provided here. There is ...,"['3 Fan', '1 Exhaust Fan', '15 Light', '1 Modu...",NaN,"['Safety4 out of 5', 'Lifestyle4 out of 5', 'E..."

In [35]:
df.loc[[311,1072,1486,3040,3875],'sector'] = 'sector 110'

In [36]:
df.shape

(3803, 21)

In [37]:
df.duplicated().sum()

0

In [38]:
df.head()

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,1 BHK Flat in Sector 71 Gurgaon,flat,signature andour heights,sector 71,0.39,9846.0,396.0,Super Built up area 325(30.19 sq.m.),1.0,1.0,2,not available,"Sector 71 Gurgaon, Gurgaon, Haryana",1.0,NaN,0 to 1 Year Old,"['Bigbasket SPR 5K DS', 'iON Digital Zone, DPG...",Signature andour heights is one of the most po...,[],NaN,"['Management4 out of 5', 'Green Area5 out of 5..."
1,2 Bedroom House for sale in Laxman Vihar,house,independent,sector 4,0.55,6813.0,807.0,Built Up area: 75,2.0,1.0,1,not available,"Laxman Vihar, Gurgaon, Haryana",1.0,NaN,5 to 10 Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...",We are proud owners of house/villa available f...,"['3 Fan', '1 Exhaust Fan', '6 Light', 'No AC',...",NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
2,4 Bedroom House for sale in Sector 1 Gurgaon,house,independent,sector 1,1.85,16003.0,1156.0,Carpet area: 1156 (107.4 sq.m.),4.0,3.0,2,not available,"975 Friends Colony, Sector 1 Gurgaon, Gurgaon,...",3.0,NaN,undefined,NaN,4bhk residential house for resale in sector 1 ...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,NaN
3,2 BHK Flat in Sector 81 Gurgaon,flat,signature global city 81,sector 81,0.82,8639.0,949.0,Built Up area: 955 (88.72 sq.m.)Carpet area: 5...,2.0,2.0,3,not available,"Sector 81, Sector 81 Gurgaon, Gurgaon, Haryana",2.0,East,undefined,"['Orris Community Center', 'HP Petrol Pump', '...",Best in class property available at sector 81 ...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment4.5 out of 5', 'Lifestyle4 out of..."
4,4 Bedroom House for sale in Sector 28 Gurgaon,house,suncity essel towers,sector 28,6.00,22222.0,2700.0,Plot area 300(250.84 sq.m.),4.0,4.0,3+,study room,"Sector 28 Gurgaon, Gurgaon, Haryana",3.0,East,10+ Year Old,"['Iffco chowk metro station', 'Mg road metro s...",5bhk spacious independent villa for sale in co...,"['5 Wardrobe', '10 Fan', '10 Light', '1 Modula...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."

In [39]:
# features to drop -> property_name, address, description, rating
df.drop(columns=['property_name', 'address', 'description', 'rating'],inplace=True)

In [40]:
df.sample(5)

,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,floorNum,facing,agePossession,nearbyLocations,furnishDetails,features
1916,flat,m3m soulitude,sector 89,1.25,8784.0,1423.0,Carpet area: 1423 (132.2 sq.m.),3.0,3.0,2,study room,3.0,NaN,Within 6 months,"['Vatika Town Square-INXT', 'Sector 86 Road', ...",NaN,"['Feng Shui / Vaastu Compliant', 'Security / F..."
2809,house,independent,sector 23,2.90,11600.0,2500.0,Plot area 2500(232.26 sq.m.),4.0,4.0,3,servant room,2.0,NaN,1 to 5 Year Old,"['HUDA Sector 23 Market', 'Palam triangle', 'P...","['4 Wardrobe', '5 Fan', '1 Exhaust Fan', '3 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard..."
378,flat,experion the heartsong,sector 108,1.60,7988.0,2003.0,Super Built up area 2003(186.08 sq.m.)Built Up...,3.0,4.0,3+,servant room,3.0,South,1 to 5 Year Old,"['Galleria 108 Mall', 'Dwarka Expressway', 'Ce...","['1 Wardrobe', '3 Fan', '1 Exhaust Fan', '3 Ge...","['Security / Fire Alarm', 'Lift(s)', 'Maintena..."
1821,flat,ss the leaf,sector 85,2.00,8305.0,2408.0,Super Built up area 2408(223.71 sq.m.)Built Up...,3.0,4.0,3,servant room,6.0,North,1 to 5 Year Old,"['Sapphire 83 Mall', 'Dwarka Expressway', 'Cen...","['6 AC', 'No Bed', 'No Chimney', 'No Curtains'...","['Feng Shui / Vaastu Compliant', 'Security / F..."
678,house,sector 15 part 2 rwa,sector 15,10.00,22222.0,4500.0,Plot area 502(419.74 sq.m.),5.0,5.0,2,not available,2.0,East,10+ Year Old,"['Hanuman Mandir', 'State bank of india ATM', ...",[],"['Feng Shui / Vaastu Compliant', 'Private Gard..."

In [41]:
# feature engineering required -> areaWithType, additionalRoom, facing, agePossession, furnishDetails, features

In [42]:
df.duplicated().sum()

122

In [43]:
df.to_csv('gurgaon_properties_cleaned_v1.csv',index=False)