In [30]:
import numpy as np 
import pandas as pd 
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder
from sklearn.model_selection import train_test_split

In [31]:
df = pd.read_csv('cars.csv')

In [32]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [33]:
df['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

In [34]:
# Split the data into training set and testing set 
X_train, X_test, y_train, y_test = train_test_split(df.drop(columns=['selling_price']), 
                                                    df['selling_price'], 
                                                    test_size=0.2,
                                                    random_state=42)

In [35]:
print(X_train.shape)
print(X_test.shape)

(6502, 4)
(1626, 4)

In [36]:
X_train.head()

        brand  km_driven    fuel                 owner
6518     Tata       2560  Petrol           First Owner
6144    Honda      80000  Petrol          Second Owner
6381  Hyundai     150000  Diesel  Fourth & Above Owner
438    Maruti     120000  Diesel          Second Owner
5939   Maruti      25000  Petrol           First Owner

### The Hard way

In [37]:
df['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

In [38]:
# Apply ordinal encoder to owner 
oe = OrdinalEncoder(categories=[['Test Drive Car', 'Fourth & Above Owner', 'Third Owner', 'Second Owner', 'First Owner']])

X_train_owner = oe.fit_transform(X_train.loc[:, ['owner']])
X_test_owner = oe.transform(X_test.loc[:, ['owner']])

In [39]:
# Convert to df 
X_train_owner_df = pd.DataFrame(X_train_owner, columns=oe.get_feature_names_out())
X_test_owner_df = pd.DataFrame(X_test_owner, columns=oe.get_feature_names_out())

In [40]:
X_train_owner_df

      owner
0       4.0
1       3.0
2       1.0
3       3.0
4       4.0
...     ...
6497    4.0
6498    3.0
6499    4.0
6500    4.0
6501    3.0

[6502 rows x 1 columns]

When i run `X_train` i got **First_owner**
 
After applying `OrdinalEncoding` we also got the 4.0 Which represent **Frist_owner**

In [41]:
df['brand'].value_counts()

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Land                6
Force               6
Isuzu               5
Kia                 4
Ambassador          4
MG                  3
Daewoo              3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [42]:
df['fuel'].value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

In [43]:
# Apply ohe to brand and fuel column 
ohe = OneHotEncoder(sparse_output=False)

X_train_brand_fuel = ohe.fit_transform(X_train[['brand', 'fuel']])
X_test_brand_fuel = ohe.transform(X_test[['brand', 'fuel']])

In [44]:
ohe.get_feature_names_out()

array(['brand_Ambassador', 'brand_Ashok', 'brand_Audi', 'brand_BMW',
       'brand_Chevrolet', 'brand_Daewoo', 'brand_Datsun', 'brand_Fiat',
       'brand_Force', 'brand_Ford', 'brand_Honda', 'brand_Hyundai',
       'brand_Isuzu', 'brand_Jaguar', 'brand_Jeep', 'brand_Kia',
       'brand_Land', 'brand_Lexus', 'brand_MG', 'brand_Mahindra',
       'brand_Maruti', 'brand_Mercedes-Benz', 'brand_Mitsubishi',
       'brand_Nissan', 'brand_Opel', 'brand_Peugeot', 'brand_Renault',
       'brand_Skoda', 'brand_Tata', 'brand_Toyota', 'brand_Volkswagen',
       'brand_Volvo', 'fuel_CNG', 'fuel_Diesel', 'fuel_LPG',
       'fuel_Petrol'], dtype=object)

In [45]:
# Converting to the Dataframe 
X_train_brand_fuel_df = pd.DataFrame(X_train_brand_fuel, columns=ohe.get_feature_names_out())
X_test_brand_fuel_df = pd.DataFrame(X_test_brand_fuel, columns=ohe.get_feature_names_out())

In [46]:
X_train_brand_fuel_df.head()

   brand_Ambassador  brand_Ashok  ...  fuel_LPG  fuel_Petrol
0               0.0          0.0  ...       0.0          1.0
1               0.0          0.0  ...       0.0          1.0
2               0.0          0.0  ...       0.0          0.0
3               0.0          0.0  ...       0.0          0.0
4               0.0          0.0  ...       0.0          1.0

[5 rows x 36 columns]

In [47]:
X_train.head()

        brand  km_driven    fuel                 owner
6518     Tata       2560  Petrol           First Owner
6144    Honda      80000  Petrol          Second Owner
6381  Hyundai     150000  Diesel  Fourth & Above Owner
438    Maruti     120000  Diesel          Second Owner
5939   Maruti      25000  Petrol           First Owner

In [48]:
X_train_rem = X_train.drop(columns=['brand', 'fuel', 'owner'], inplace=True)
X_test_rem = X_test.drop(columns=['brand', 'fuel', 'owner'], inplace=True)

In [49]:
X_train = pd.concat([X_train_rem, X_train_owner_df, X_train_brand_fuel_df], axis=1)
X_test = pd.concat([X_test_rem, X_test_owner_df, X_test_brand_fuel_df], axis=1)

In [50]:
X_train.head()

   owner  brand_Ambassador  brand_Ashok  ...  fuel_Diesel  fuel_LPG  fuel_Petrol
0    4.0               0.0          0.0  ...          0.0       0.0          1.0
1    3.0               0.0          0.0  ...          0.0       0.0          1.0
2    1.0               0.0          0.0  ...          1.0       0.0          0.0
3    3.0               0.0          0.0  ...          1.0       0.0          0.0
4    4.0               0.0          0.0  ...          0.0       0.0          1.0

[5 rows x 37 columns]

### The Easy way

Let's implement this in easy way.

In [51]:
from sklearn.compose import ColumnTransformer

In [53]:
df = pd.read_csv('cars.csv')

In [54]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

Here we are also going to encode column in same way 
- Owner - We'll apply OrdinalEncoding 
- brand & fuel - we'll apply OneHotEncoding

In [69]:
# Split the data into training set and testing set 
X_train, X_test, y_train, y_test = train_test_split(df.drop(columns=['selling_price']), 
                                                    df['selling_price'], 
                                                    test_size=0.2,
                                                    random_state=42)

In [70]:
transformer = ColumnTransformer(
    [
        ("ordinal", OrdinalEncoder(
                categories=[[
                    'Test Drive Car',
                    'Fourth & Above Owner',
                    'Third Owner',
                    'Second Owner',
                    'First Owner'
                ]],
                handle_unknown='use_encoded_value',
                unknown_value=-1
            ), ['owner']),
        
        ("onehot", OneHotEncoder(sparse_output=False, handle_unknown='ignore'), ['brand', 'fuel'])
    ],
    remainder='passthrough'
)

# setting to get a pandas df
# transformer.set_output(transform='pandas')

In [71]:
X_train_transformed = transformer.fit_transform(X_train)
X_test_transformed = transformer.transform(X_test)

In [73]:
transformer.set_output(transform='pandas')

ColumnTransformer(remainder='passthrough',
                  transformers=[('ordinal',
                                 OrdinalEncoder(categories=[['Test Drive Car',
                                                             'Fourth & Above '
                                                             'Owner',
                                                             'Third Owner',
                                                             'Second Owner',
                                                             'First Owner']],
                                                handle_unknown='use_encoded_value',
                                                unknown_value=-1),
                                 ['owner']),
                                ('onehot',
                                 OneHotEncoder(handle_unknown='ignore',
                                               sparse_output=False),
                                 ['brand', 'fuel'])])

In [74]:
transformer.fit_transform(X_train)

      ordinal__owner  ...  remainder__km_driven
6518             4.0  ...                  2560
6144             3.0  ...                 80000
6381             1.0  ...                150000
438              3.0  ...                120000
5939             4.0  ...                 25000
...              ...  ...                   ...
5226             4.0  ...                120000
5390             3.0  ...                 80000
860              4.0  ...                 35000
7603             4.0  ...                 27000
7270             3.0  ...                 70000

[6502 rows x 38 columns]

In [75]:
transformer.feature_names_in_

array(['brand', 'km_driven', 'fuel', 'owner'], dtype=object)

In [ ]:
transformer.n_