# Encoding

## What Encoding Does
- Encoding converts categorical features into numerical features by applying various transformations.

## Why Do We Need Encoding?
- We need encoding because machine learning algorithms cannot work with categorical features directly.
- Algorithms (computers) only understand numbers.

## What Are the Ways to Encode Features?
- There are several prebuilt encoders available, and you can also build your own custom encoder.

---

## Types of Categorical Data
There are two types of categorical data:

1. **Ordinal Data**
   - Categories that have an inherent order.
   - Example: `Poor`, `Average`, `Good`
   - Order: `Good > Average > Poor`

2. **Nominal Data**
   - Categories that have no inherent order.
   - Example: `Pen`, `Paper`, `Notebook`
   - No category can be ranked as greater or smaller.

---

## Ordinal Categorical Encoding
- To convert ordinal categorical data into numerical data, scikit-learn provides **Ordinal Encoding**.

## How Ordinal Encoding Works
```bash
OrdinalEncoder(categories=[['Poor', 'Average', 'Good']])
```
Resulting Mapping

Poor → 1

Average → 2

Good → 3

## 1. Ordinal Encoding

In [2]:
import numpy as np 
import pandas as pd

In [4]:
df = pd.read_csv('customer (1).csv')

In [5]:
df.head()

   age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

- **Review** column have some kind of order `Poor`, `Average` and `good` 
- **Education** column also have order `School`, `UG` and `PG` 
- For these two column we'll use **OrdinalEncoding** 
- But **Gender** column have no order 
- For **Gender** column we'll use **ONEHOTENCODING**

In [6]:
from sklearn.preprocessing import OrdinalEncoder
from sklearn.model_selection import train_test_split

In [23]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 2:4], df.iloc[:, -1], test_size=0.2)

In [24]:
X_train

     review education
31     Poor    School
25     Good    School
20  Average    School
15     Poor        UG
11     Good        UG
28     Poor    School
7      Poor    School
6      Good    School
38     Good    School
9      Good        UG
18     Good    School
24  Average        PG
8   Average        UG
27     Poor        PG
29  Average        UG
41     Good        PG
40     Good    School
1      Poor        UG
45     Poor        PG
44  Average        UG
35     Poor    School
42     Good        PG
10     Good        UG
16     Poor        UG
2      Good        PG
13  Average    School
5   Average    School
21  Average        PG
22     Poor        PG
32  Average        UG
37  Average        PG
49     Good        UG
39     Poor        PG
23     Good    School
0   Average    School
34  Average    School
36     Good        UG
12     Poor    School
48     Good        UG
3      Good        PG

In [25]:
print(X_train.shape)
print(X_test.shape)

(40, 2)
(10, 2)

In [26]:
df['education'].value_counts()

education
PG        18
School    16
UG        16
Name: count, dtype: int64

In [27]:
df['review'].value_counts()

review
Poor       18
Good       18
Average    14
Name: count, dtype: int64

In [28]:
# Specifying order 
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [29]:
X_train = oe.fit_transform(X_train)
X_test = oe.transform(X_test)

# Why we didin't use fit_transform in term of X_test 
# Because our model learn pattern from traing data not from testing data

In [30]:
X_train

array([[0., 0.],
       [2., 0.],
       [1., 0.],
       [0., 1.],
       [2., 1.],
       [0., 0.],
       [0., 0.],
       [2., 0.],
       [2., 0.],
       [2., 1.],
       [2., 0.],
       [1., 2.],
       [1., 1.],
       [0., 2.],
       [1., 1.],
       [2., 2.],
       [2., 0.],
       [0., 1.],
       [0., 2.],
       [1., 1.],
       [0., 0.],
       [2., 2.],
       [2., 1.],
       [0., 1.],
       [2., 2.],
       [1., 0.],
       [1., 0.],
       [1., 2.],
       [0., 2.],
       [1., 1.],
       [1., 2.],
       [2., 1.],
       [0., 2.],
       [2., 0.],
       [1., 0.],
       [1., 0.],
       [2., 1.],
       [0., 0.],
       [2., 1.],
       [2., 2.]])

In [31]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [32]:
oe.feature_names_in_

array(['review', 'education'], dtype=object)

In [33]:
oe.inverse_transform(np.array([0, 2]).reshape(1, 2))

array([['Poor', 'PG']], dtype=object)

In [34]:
oe.inverse_transform(np.array([1, 1]).reshape(1, 2))

array([['Average', 'UG']], dtype=object)

In [35]:
oe.get_feature_names_out()

array(['review', 'education'], dtype=object)

In [ ]:
# handle unknown
# What if we enter some random value that we didn't handle while encoding. 
# Sklearn provide some feature but default you'll get error. 
oe.transform(np.array(['Poor','college']).reshape(1,2))

/Users/sanjaymahto/Python/.venv/lib/python3.13/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

ValueError: Found unknown categories [np.str_('college')] in column 1 during transform

In [38]:
# Set unknown values 
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']], 
                    handle_unknown='use_encoded_value', 
                    unknown_value= -1 # use can also try out any constant values 
)

In [39]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,2:4], df.iloc[:,-1], test_size=0.2)

In [40]:
X_train = oe.fit_transform(X_train)
oe.transform(np.array(['Poor','college']).reshape(1,2))

/Users/sanjaymahto/Python/.venv/lib/python3.13/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

array([[ 0., -1.]])

In [41]:
# Handling infrequent value. 
X = np.array([['dog'] * 5 + ['cat'] * 20 + ['rabbit'] * 10 +['snake'] * 3 + ['horse'] * 2], dtype=object).T
X

array([['dog'],
       ['dog'],
       ['dog'],
       ['dog'],
       ['dog'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['rabbit'],
       ['rabbit'],
       ['rabbit'],
       ['rabbit'],
       ['rabbit'],
       ['rabbit'],
       ['rabbit'],
       ['rabbit'],
       ['rabbit'],
       ['rabbit'],
       ['snake'],
       ['snake'],
       ['snake'],
       ['horse'],
       ['horse']], dtype=object)

In [44]:
enc = OrdinalEncoder(max_categories=3).fit(X) # Max_Category how how many category you want this is hypertunable parameter.

In [45]:
enc.infrequent_categories_

[array(['dog', 'horse', 'snake'], dtype=object)]

In [ ]:
enc.transform(np.array([['cat', 'rabbit', 'snake', 'dog']]).reshape(4, 1))

array([[0.],
       [1.],
       [2.],
       [2.]])

Snake and dog get 2,2 becuase these two were infrequent_category.

In [47]:
enc.transform(np.array([['cat', 'rabbit', 'snake', 'dog', 'horse']]).reshape(5, 1))

array([[0.],
       [1.],
       [2.],
       [2.],
       [2.]])

In [48]:
# Handling missing value 

# Example categorical data with missing value 
# Although we handle missing value in data preprocssing stage. 
data = [['Cat'], [np.nan], ['Dog'], ['Fish'], [np.nan]]

# Setting encoded_missing_value to -1 
# Indicating we want missing values to be encoded as -1 

encoder = OrdinalEncoder(encoded_missing_value=-1)

encoded_data = encoder.fit_transform(data)

print(encoded_data)

[[ 0.]
 [-1.]
 [ 1.]
 [ 2.]
 [-1.]]

## LabelEncoder

## Label Encoding

- We use **Label Encoding** on the **output (target) column**.
- `LabelEncoder` does **not follow any mathematical or logical order**.
- It assigns values **based on alphabetical order**.
- There is **no semantic meaning** behind the assigned numbers.

### Key Characteristics
- No logic
- No inherent order
- Purely alphabetical mapping

### Example
```text
Classes: Ham, Spam
```
After Label Encoding:

Ham  → 0

Spam → 1

Note: LabelEncoder starts from 0, not 1.

### When Should We Use LabelEncoder?

- We **must use LabelEncoder for classification problems** to encode the target variable.

This works because class labels are **identifiers**, not quantities.

The model does **not assume any mathematical relationship** between classes.

### Why Don’t We Use Label Encoding on Input Features?
#### Reason:

- LabelEncoder does **not preserve any meaningful order.**

It assigns values purely based on **alphabetical order.**

As a result, the model may learn **false relationships** between categories.

It fails to capture any **real-world meaning** of the feature.

Example (Wrong Usage)
```text
Education Level: High School, Bachelor, Master
```
Alphabetical encoding:
```text
Bachelor    → 0
High School → 1
Master      → 2
``` 
This order is logically incorrect and misleads the model.

### Important Note
- You can technically apply LabelEncoder to input features,

- but it is **not recommended** because it introduces **artificial order** and **incorrect assumptions** into the model.

In [49]:
df.head()

   age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

In [50]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 2:4], df.iloc[:, -1], test_size=0.2)

In [54]:
X_train.head()

   review education
25   Good    School
36   Good        UG
33   Good        PG
42   Good        PG
17   Poor        UG

In [55]:
y_train.head()

25     No
36    Yes
33    Yes
42    Yes
17    Yes
Name: purchased, dtype: str

In [51]:
print(X_train.shape)
print(X_test.shape)

(40, 2)
(10, 2)

In [56]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [57]:
y_train = le.fit_transform(y_train)
y_test = le.transform(y_test)

In [58]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [59]:
le.inverse_transform(np.array([1, 1, 0, 0]))

array(['Yes', 'Yes', 'No', 'No'], dtype=object)

## OneHotEncoding

Why we can't use Ordinal Encoder for nomial feature 
Because ordinal Encoder assign a number to each category that's create a ordering system. When we have ordinal data then it's good but in case of Green, blue and red. 

The Real question: 
Is green greater then blue. 
No right. 

Now we need a Method which introduce 
- Each category should be 
    - Independent 
    - No bigger or smaller than others 
    - Clearly identifiable

So what if instead of one column we create one column per category?

We use OneHotEncoding on nominal feature into numercial feature. 

How OneHotEncoding Works 
OneHotEncoding represent each category as binary vector. 
Example Apple, Orange, banana and Guava. 
Write GPT this in Markdown style


Pros: 
Independent

In [134]:
data = pd.read_csv('cars.csv')

In [135]:
data.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [62]:
data.isnull().sum()

brand            0
km_driven        0
fuel             0
owner            0
selling_price    0
dtype: int64

In [63]:
data.duplicated().sum()

np.int64(1678)

In [136]:
data.columns

Index(['brand', 'km_driven', 'fuel', 'owner', 'selling_price'], dtype='str')

In [161]:
data['brand'].nunique()

32

In [162]:
X = data[['brand','fuel']]
y = data['selling_price']

In [185]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [160]:
X_train.head()

        brand  km_driven
6518     Tata       2560
6144    Honda      80000
6381  Hyundai     150000
438    Maruti     120000
5939   Maruti      25000

In [164]:
X_train['fuel'].nunique()

4

In [72]:
X_train['fuel'].nunique()

4

In [73]:
X_train['owner'].nunique()

5

In [ ]:
X_train['owner'].value_counts()
# This is ordinal column

owner
First Owner             4240
Second Owner            1684
Third Owner              433
Fourth & Above Owner     141
Test Drive Car             4
Name: count, dtype: int64

In [111]:
X_train['brand'].nunique()

32

In [ ]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(sparse_output=False, dtype=np.int32)

In [187]:
X_train = ohe.fit_transform(X_train)

In [167]:
X_train = ohe.fit_transform(X_train).toarray()
X_train

AttributeError: 'numpy.ndarray' object has no attribute 'toarray'

In [188]:
X_train.shape

(6502, 36)

In [142]:
ohe.categories_

[array(['Ambassador', 'Ashok', 'Audi', 'BMW', 'Chevrolet', 'Daewoo',
        'Datsun', 'Fiat', 'Force', 'Ford', 'Honda', 'Hyundai', 'Isuzu',
        'Jaguar', 'Jeep', 'Kia', 'Land', 'Lexus', 'MG', 'Mahindra',
        'Maruti', 'Mercedes-Benz', 'Mitsubishi', 'Nissan', 'Opel',
        'Peugeot', 'Renault', 'Skoda', 'Tata', 'Toyota', 'Volkswagen',
        'Volvo'], dtype=object),
 array(['CNG', 'Diesel', 'LPG', 'Petrol'], dtype=object)]

In [143]:
ohe.feature_names_in_

array(['brand', 'fuel'], dtype=object)

In [144]:
ohe.n_features_in_

2

In [190]:
names = ohe.get_feature_names_out()

In [ ]:
pd.DataFrame(X_train,columns=names)

,brand_Ambassador,brand_Ashok,brand_Audi,brand_BMW,brand_Chevrolet,brand_Daewoo,brand_Datsun,brand_Fiat,brand_Force,brand_Ford,...,brand_Renault,brand_Skoda,brand_Tata,brand_Toyota,brand_Volkswagen,brand_Volvo,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol
0,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6497,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
6498,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
6499,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
6500,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
6501,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [192]:
ohe.inverse_transform(np.array([0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0.]).reshape(1,36))

ValueError: Samples [0] can not be inverted when drop=None and handle_unknown='error' because they contain all zeros

In [193]:
ohe.inverse_transform(X_train[:1])

array([['Tata', 'Petrol']], dtype=object)

In [194]:
row = np.zeros(36)

row[names.tolist().index("brand_Maruti")] = 1
row[names.tolist().index("fuel_Diesel")] = 1

ohe.inverse_transform(row.reshape(1, -1))

array([['Maruti', 'Diesel']], dtype=object)

In [195]:
# Drop one to reduce the multicolinearty
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

ohe = OneHotEncoder(drop='first', sparse_output=False)
ohe.fit_transform(X_train).shape

(6502, 34)

In [196]:
ohe.drop_idx_

array([0, 0], dtype=object)

In [197]:
# Handling rare category 
X_train['brand'].value_counts()

brand
Maruti           1953
Hyundai          1127
Mahindra          635
Tata              586
Toyota            391
Honda             369
Ford              320
Chevrolet         185
Renault           183
Volkswagen        154
BMW                96
Skoda              82
Nissan             62
Jaguar             59
Volvo              54
Datsun             48
Mercedes-Benz      43
Fiat               35
Audi               30
Jeep               26
Lexus              22
Mitsubishi         13
Force               6
Land                5
Kia                 4
Ambassador          3
MG                  3
Daewoo              3
Isuzu               2
Ashok               1
Peugeot             1
Opel                1
Name: count, dtype: int64

In [198]:
# using min frequency 

ohe = OneHotEncoder(sparse_output=False, min_frequency=100)
ohe.fit_transform(X_train).shape

(6502, 14)

In [199]:
ohe.get_feature_names_out()

array(['brand_Chevrolet', 'brand_Ford', 'brand_Honda', 'brand_Hyundai',
       'brand_Mahindra', 'brand_Maruti', 'brand_Renault', 'brand_Tata',
       'brand_Toyota', 'brand_Volkswagen', 'brand_infrequent_sklearn',
       'fuel_Diesel', 'fuel_Petrol', 'fuel_infrequent_sklearn'],
      dtype=object)

In [200]:
# using max_categories 
ohe = OneHotEncoder(sparse_output=False, handle_unknown='ignore', max_categories=15)
ohe.fit_transform(X_train).shape

(6502, 19)

In [201]:
# how to handle unknown category
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

ohe = OneHotEncoder(drop='first',sparse_output=False)
ohe.fit_transform(X_train)

ohe.transform(np.array(['local','Petrol']).reshape(1,2))

/Users/sanjaymahto/Python/.venv/lib/python3.13/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

ValueError: Found unknown categories [np.str_('local')] in column 0 during transform

In [202]:
ohe = OneHotEncoder(sparse_output=False, handle_unknown='ignore')
ohe.fit_transform(X_train)

ohe.transform(np.array(['local','Petrol']).reshape(1,2))

/Users/sanjaymahto/Python/.venv/lib/python3.13/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 1.]])

## LabelBinarizer

In [203]:
from sklearn.preprocessing import LabelBinarizer

# Sample target variable for a multi-class classification problem 
y = ['cat', 'dog', 'fish', 'dog', 'cat']

# Initialize the LabelBinarizer 
lb = LabelBinarizer()

# Fit and transform the target variable
y_binarized = lb.fit_transform(y)

print("Binarized labels:\n", y_binarized)

# Inverse transform to recover original labels
y_original = lb.inverse_transform(y_binarized)

print("Original labels:\n", y_original)

Binarized labels:
 [[1 0 0]
 [0 1 0]
 [0 0 1]
 [0 1 0]
 [1 0 0]]
Original labels:
 ['cat' 'dog' 'fish' 'dog' 'cat']